### ISSUE TITLE
Driver allows form submit with invalid destination zip code

### ISSUE THREAD

**Issue by jkbits1** [voteamerica/voteamerica.github.io#100]
Collection zip code is enforced and shown to user. Destination is not shown and is allowed when invalid

**Comment by richardwestenra** [comment]
@jkbits1 This should have been fixed in #103, can you please confirm?

**Comment by jkbits1** [comment]
when last seen, this was still the case for driver. Will review and let you know

**Comment by jkbits1** [comment]
resolved, thanks @richardwestenra :+1:
