### ISSUE TITLE
Rider prevents form submit with invalid collection zip code but does not highlight as error

### ISSUE THREAD

**Issue by jkbits1** [voteamerica/voteamerica.github.io#101]
Rider form does not highlight an invalid zip code but prevents form submission

**Comment by jkbits1** [comment]
great, will test this out soon

**Comment by richardwestenra** [comment]
@jkbits1 Can you confirm this issue is resolved?

**Comment by jkbits1** [comment]
thanks for the reminder, I'm not sure and will review today

**Comment by jkbits1** [comment]
great @richardwestenra this is resolved :smile:
