### ISSUE TITLE
iframe for map inclusion

### ISSUE THREAD

**Issue by timkeane** [voteamerica/voteamerica.github.io#118]
the sample map can be included in an iframe on any page desired.
src attribute of the iframe should point to carpool-map/index.html page https://github.com/voteamerica/voteamerica.github.io/blob/master/carpool-map/index.html

note that the data currently displayed on the map is mock data and it must ultimately be provided 
from the backend in some fashion. carpool-map/js/map.js will require updates once backend data 
endpoints are available.

carpool-map/css/map.css may be edited so that button styles are consistent with overall site theme.
I can make the css changes provided direction.

**Comment by sasjkia** [comment]
has this now been taken care of?

**Comment by langdonms** [comment]
Yes, no longer needed as the map will be inserted to `div` element on the main page.
