### ISSUE TITLE
Big blue Add [Time] button is not intuitive

### ISSUE THREAD

**Issue by dmilet** [voteamerica/voteamerica.github.io#124]
On my screen (Chrome Browser) the location of the Add [Time] button is top right compared to where my eyes are when I use the slider to select time. 
I naturally move my eyes down the page
Blue button is overlooked.
Submit button still worked, and form was submitted without time information.

rider payload: {
    "_redirect": "file:///C:/Users/David/Desktop/voteamerica.github.io/index.htmlthanks.html",
    "RiderDate": "Monday, Oct 24",
    **"AvailableRideTimesJSON": "",**
    "RiderCollectionZIP": "20111",
    "RiderDropOffZIP": "20111",
    "TotalPartySize": "1",
    "RiderAccommodationNotes": "Hello",
    "RiderFirstName": "DAVID",
    "RiderLastName": "MILET",
    "RiderEmail": "david.milet@gmail.com",
    "RiderPhone": "555-555-5555",
    "RiderLegalConsent": "on",
    "RiderWillBeSafe": "on",
    "RiderWillNotTalkPolitics": "on",
    "PleaseStayInTouch": "on",
    "RiderVotingState": "MO"
}

**Comment by sasjkia** [comment]
We should also not allow for submissions without time input.

**Comment by richardwestenra** [comment]
@sasjkia @dmilet I totally agree with you! It’s been bugging me too, but I’ve been trying to focus on other stuff in the meantime. My suggestions:

1. Quick fix: Revert to one column, so you don’t miss the button. It would look like it does on mobile.
2. Change the inline datepicker and range slider to a date input and two time inputs, and reveal the datepicker/timepicker UI elements only on focus, so that these elements don’t take up as much vertical real estate. This should make it easier to grasp the whole UI when it’s all visible on screen at once. Kinda like this:
![image](https://cloud.githubusercontent.com/assets/1155816/19481449/df4b894c-9545-11e6-8425-c6bd4f942d22.png)

**Comment by jkbits1** [comment]
@richardwestenra I did prefer the button below the slider. When using the mouse it breaks the flow. I haven't mentioned before as the debate may never end :smile: 

Overall, there is two issues here. One is the UI/UX of the the button. Second is the issue of allowing submission with no times (especially as the user may not be aware that this makes their submission totally pointless).

@dmilet @sasjkia @richardwestenra Is there a specific reason that we have allowed submission without date/times? Now we have code that sends the date/times, we have a check that exists where we can prevent form submission.

**Comment by jkbits1** [comment]
1. as above, don't want to play UI ping-pong :smile: so up to others

2. er, the slider may not be perfect but it seems pretty good to me. very visually intuitive. I've wondered about screen-readers etc . I'm taking a guess that people with issues like that are a larger than usual proportion of our users. still, we have phone assistance for people so others can enter the form info

3. I may have misunderstood the code and it may not fit in with our elegant error UX. But when we create the date/time list we can tell if it's empty and could cancel the form submission there. and if not, we can really, really flag it to the user at that point

Overall, I think the picker solution is decent, and it's going to be hard to improve it in our timeframe. I've used it a lot when testing, and for something that is complex, it is intuitive, visually clear, works well, and supports changes in case of user mistakes

**Comment by richardwestenra** [comment]
@jkbits1 I broadly agree. 👍 I think it's mainly just the lack of accessibility/standards-compliance of those components that bug me, but for now, as we're in a hurry and everything, they're perfect.

Regarding point 3, our current setup is using native `required` attributes for validation, with a veneer of Bootstrap Validator to improve support and styling. idk how well those two custom inputs will work with it but I'm gonna look into it now.

**Comment by sasjkia** [comment]
@richardwestenra i thought the ui for this worked really well and it would be great if we could find a way to prevent people from submitting without an entry...

Re accessibility: What happens to the current version when you use screen readers?

**Comment by richardwestenra** [comment]
@sasjkia ok cool. I'm working on the validation right now.

As for accessibility: The datepicker might be accessible for blind users, but I'm not sure. The range slider is completely hidden/unusable for screenreader users.

**Comment by sasjkia** [comment]
Could we have the option to click a link to switch to sreenreader-friendly version and then they manually input timeframes for each date selected?

i think the current version is really elegant and achieves everything we want to achieve but of course there needs to be the option for people with visual disabilities.

**Comment by richardwestenra** [comment]
Yeah there are ways we could make this work properly for people with disabilities but it would require quite a significant time investment.

I probably wouldn't have a link to click to view the screenreader version, I'd add a hidden accessible version. But once you've made a working accessible alternative, you probably might as well replace our existing version with it.

Sorry, I'm not saying we shouldn't include a range slider and a calendar. I haven't explained myself very well, I haven't had the chance to put together a proper design mockup. I would include these elements, but as floating panes that are visible only when the user focuses inside a date/time text input. Again, this is just an idea, I'd ideally like to spend some time working on some concepts. argh  ⏳

**Comment by jkbits1** [comment]
screen-readers and their users are an important issue and I've tried hard to consider that for other issues. However, from my perspective (which may be incorrect) we've gone with this approach for so long it's going to be hard to change course this close to the deadline. 

we are looking to have phone line support, perhaps we could flag to screen-reader users that it is an issue. at least it would be clear what the situation was for them

however, it's not me that's either coding it or using it etc etc

I may finish commenting here (I can't really add anything useful further), but I have a contact who's given us good advice in this area before if we have a couple of clear questions

**Comment by richardwestenra** [comment]
+1 @jkbits1. idk whether we actually have enough time for this before the election, with everything else that needs doing :(. I would love this site to be perfectly accessible but we've inherited this code and don't have time to change everything.

For what it's worth, this is a bit closer to what I was envisioning:
![image](http://g.recordit.co/qBRUKuSx6C.gif)
(Except imagine it with ❌ delete buttons next to each row, and also with a time range slider for each row that's hidden by default but is revealed on focus, kinda like the datepicker.

**Comment by jkbits1** [comment]
@dmilet @richardwestenra the revised time picker looks great to me, and generally appears different to when this issue was opened. Can we close it?

**Comment by richardwestenra** [comment]
Yup, definitely :). Thanks for the reminder!
