### ISSUE TITLE
Delete Time (red cross) does not delete time entry from AvailableDriveTimesJSON

### ISSUE THREAD

**Issue by dmilet** [voteamerica/voteamerica.github.io#125]
I tested this on the DRIVER side only.

I had a form which I had submitted with one time interval only.
Went back to the form, added 2nd time interval, then removed the first interval.

Both intervals were submitted.

driver payload: {
    "_redirect": "file:///C:/Users/David/Desktop/voteamerica.github.io/index.htmlthanks.html",
    "DriverDate": "Monday, Oct 24",
    "AvailableDriveTimesJSON": "2016-10-24T04:00:00.000Z/2016-10-24T08:00:00.000Z|2016-10-24T08:00:00.000Z/2016-10-24T12:00:00.000Z",
    "DriverCollectionZIP": "20111",
    "DriverCollectionRadius": 0,
    "SeatCount": "1",
    "DriverHasInsurance": "on",
    "DriverLicenceNumber": "xxx",
    "DriverFirstName": "DAVID",
    "DriverLastName": "MILET",
    "DriverEmail": "david.milet@gmail.com",
    "DriverPhone": "555-555-5555",
    "DrivingOBOOrganizationName": "",
    "RidersCanSeeDriverDetails": "on",
    "DriverWillTakeCare": "on",
    "DriverWillNotTalkPolitics": "on",
    "PleaseStayInTouch": "on"
}

**Comment by richardwestenra** [comment]
Good catch, thanks. I'll take this.

**Comment by richardwestenra** [comment]
@jkbits1 I'd love to merge #117 (the datetime refactoring) before fixing this bug, as both involve simplifying the datetime JS. What do you think?

**Comment by jkbits1** [comment]
@richardwestenra the date/times are essential for the matching engine to work, and without the time to create tests this code is vulnerable to changes/improvements.

I really don't want to refactor the date time code we have any time in the next few days/week. I'm still looking at further changes to the format provided for the backend. It's ok to take out variables that aren't used (or preferably flag them with comments so changes can be checked). When I write some code and it is refactored, then I go back to it, I have to re-learn how it is done

further changes may depend on the moment.js library. when this code is settled, we can address that

from my last comment, I thought that the date/time code in https://github.com/voteamerica/voteamerica.github.io/pull/117
still had issues. Everything else about the PR was good, and I think was merged in another PR

**Comment by richardwestenra** [comment]
@jkbits1  okay cool, thanks 👍

**Comment by richardwestenra** [comment]
This issue should be fixed as of #128.
