### ISSUE TITLE
Change text in DRIVER and RIDER boxes on the landing page

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#130]
We need to be as clear as possible in helping people understand why we're doing this.

**RIDER box:**
Need a ride to the polls or voter I.D. office?

Fill in the form to let us know when and where you need a ride. We’ll do our best to match you with a driver!

** #DRIVER box:**
Do you have a spare seat to help get somebody to the polls or voter I.D. office?

Fill in the form to let us know when and where you’ll be driving, and we’ll match you with a rider!

**Comment by richardwestenra** [comment]
Completed by @JackOddy in PR #136
