### ISSUE TITLE
Change the text that appears after submission of the RIDER form

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#131]
Please change to the following text

**RIDER**
CONGRATULATIONS
on taking this step to claim your vote!

We’ve sent you a message confirming that we’ve received your request.

Your ride request reference number is: [insert from URL after form submission]
Please keep this reference in case you need to manage your ride request.
To view or manage your ride request, visit our [self-service portal: http://www.carpoolvote.com/self-service/]

`What happens next?`
- Our system will match you with potential drivers, based on the information you’ve provided.
- We'll let you know as soon as a driver has accepted your request.
- The driver will then get in touch with you through the preferred method of contact you specified on the form.
- It's then up the you and the driver to arrange when and where you'd like to meet, and any other details of your trip.

Let your friends know!
_[Tweet button: I’ve just signed up for a ride to #ClaimMyVote. You can do the same on @CarpoolVote.com. This Election will be close. Let's #CountEveryVote.]
[Facebook button]_

**DRIVER**

THANK YOU
for offering a fellow American a ride to claim their vote!

Together, our driving volunteers could help shape the outcome of this election.

We’ve sent you a message confirming that we’ve received your offer.

Your driver offer reference is: [insert from URL after form submission]
Please keep this reference in case you need to manage your offer.
To view or manage your matches, visit our  [self-service portal: http://www.carpoolvote.com/self-service/]

`What happens next?`
- Our system will now match you with a passenger(s), based on the information you’ve provided. 
- We'll send you a notification of every ride request that matches your criteria.
- You can then accept as many ride requests as work for you.
- Once you have accepted a ride request, we'll send you a message with the rider's contact details.
- It's then up the you and the rider to arrange when and where you'd like to meet, and any other details of your trip.

Let your friends know!
_[Tweet button: I’ve just signed up to #DriveToVote this #Election2016. Pls do the same on @CarpoolVote.com. This election will be close! #DemocracyForAll]
[Facebook button]_

**Comment by richardwestenra** [comment]
We also need to improve the design of these pages to match the rest of the site, and to show a custom link to the match self-service page.

**Comment by sasjkia** [comment]
ok, i've updated the text to include self-service page and uuid

**Comment by richardwestenra** [comment]
@sasjkia Thanks!

@jkbits1 @dmilet Is http://www.carpoolvote.com/self-service/?uuid=XXXXX okay as a URL?

**Comment by jkbits1** [comment]
@richardwestenra you probably are very aware of this, but the self service page accepts either or both of uuid_driver and uuid_rider. this is now specified in the user stories doc if you want to see more info

**Comment by misteranderson** [comment]
Can we split out the self-service into rider vs. driver to keep the functionality / messaging clear?

**Comment by sasjkia** [comment]
These look great! :D

**Comment by sasjkia** [comment]
Text following DRIVER form submission is for RIDERS
