### ISSUE TITLE
DRIVER signup form text updates

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#133]
- [x] Change "When and where can you pick someone up?" to "What can you offer?"
- [x] Change "Date available" to "Dates available". Underneath this heading, add: "On what date(s) would you be a available to give rides?" We'll propose matches for all of the dates that you pick."
- [x] Underneath the "Time range available" heading, add: "Which times slots on this date would you be available to give rides? You can pick multiple time slots, on different dates or the same date."
- [x] Change "Collection zip code" to "Pick up zip code". Change text in the box to "Where can you pick up the rider?"
- [x] Hide "I am driving in an official capacity on behalf of a registered organization" from the front end: This should still be an entry in the database - which can be fed via CSV from our partners. We just don't want people to be able to enter it at the front end.

**Comment by richardwestenra** [comment]
@sasjkia Regarding the last point here, did you mean that we should completely delete the registered organisation checkbox and input from the form?

**Comment by sasjkia** [comment]
@richardwestenra this should be hidden from the front end. We still need the entry in the database but not the option for anyone to input on the front end.

**Comment by richardwestenra** [comment]
Ok I think I understand. Sorry, the confusion here is that in specific CSS dev terms 'hidden' and 'deleted' mean two different things, so @joesweeny has kept the input in the form but made it invisible (i.e. 'hidden'). I don't mean to be pedantic here, sorry!
I'm going to interpret you to mean that that it should be completely removed from the form, and that if people want to add this in the database then they can do that manually elsewhere.

**Comment by richardwestenra** [comment]
Fixed in #139
