### ISSUE TITLE
Update project readme and add documentation

### ISSUE THREAD

**Issue by richardwestenra** [voteamerica/voteamerica.github.io#142]
- [x] Add [contribution guidelines](https://github.com/blog/1184-contributing-guidelines) section
- [x] Add a code of conduct.
- [x] Add details about the project's aims, deadlines, contributors, how to sign up to the Slack group, and who to contact.
- [x] Add information in 'How to contrubute' about how to get the project up and running locally. (Personally I use [Browsersync](https://www.browsersync.io/) to run a local Node server and watch files with `browser-sync start -s -f "**/*"`, but any local server will do).
- [x] Under 'Technical', add info about the different APIs we're using ~(v1.1 and v2.0)~ (live and test)
- [x] Under 'Technical', add info about how everything works and where files should go.
- [x] Under 'Technical', add info about souls2thepolls and tinyQuery.

**Comment by cancinos** [comment]
#150

**Comment by cancinos** [comment]
Readme template update #150
