### ISSUE TITLE
Add "Preferred method of contact" to DRIVER signup form

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#145]
Preferred method of contact
- [ ] Email
- [ ] Phone
- [ ] SMS

This should look and be positioned the same is in the RIDER signup form

Please communicate with backend about this before merging

**Comment by richardwestenra** [comment]
@sasjkia I'm assuming that the email checkbox should toggle whether email is required, same as for the rider form?
