### ISSUE TITLE
Preferred method(s) of contact and notifications

### ISSUE THREAD

**Issue by dmilet** [voteamerica/voteamerica.github.io#148]
This is issue is actually to clarify the requirements.

Do the "Preferred Method(s) of Contact" apply to communication between riders and drivers only, or should the system honor those preferences too?
Obviously the system cannot make phone calls...

I was planning to generate e-mail notifications if the user entered an e-mail address, irrespective of the "Preferred Method of Contact" choice from the user. Same approach for SMS. 

Note that a rider will get a notification
- after he/she submits a ride request,
- after he/she cancels a ride request,
- after a driver has confirmed a match
- after he/she cancels a confirmed match

A driver will get a notification
- after he/she submits a drive offer,
- after he/she cancels a drive offer,
- after he/she has confirmed a match
- after he/she cancels a confirmed match
- after new matches are added by the match engine. We definitely don't want to send one notification per match. Maybe one notification every 4 hours would be ok, but only if new matches are adde for this driver ?

**Comment by sasjkia** [comment]
@dmilet my initial intention was simply to provider the driver with information on how to get in touch with the rider.

But then I thought the user stories you wrote made sense and could save us money.

Good point though - driver check boxes should have 2 options only: Email and SMS.

**Comment by dmilet** [comment]
@sasjkia Since riders don't contact drivers, for whom do we collect the driver's preferred method of contact ? 
And what do you mean the stories I wrote could save us money ?

**Comment by sasjkia** [comment]
@dmilet from your stories, I understood that the driver preferred method of contact would allow us to tailor whether we send them sms or email notifications.

This would be cheaper if we paid per email/sms.

Of course, if this makes too much work for us, we could just skip the feature altogether and send them both.

For the riders, we should assume that the preferred method of contact is for the drivers to get in touch. And we should specify this in the text on the form.

**Comment by sasjkia** [comment]
@dmilet and for us to get in touch with rider, i would suggest sms at the minimum (as many may not have email) but both sms and email is preferable because they may give out a home phone number.

**Comment by sasjkia** [comment]
@dmilet i've reviewed this and think we need to send email only if a riders specifies that they prefer driver contact via email. And send both email and SMS if they specify that they prefer contact via either SMS or phone (as phone may be a landline).

I've also created an issue for the text on the front end of the rider form to be updated. Does this work?

**Comment by sasjkia** [comment]
@dmilet would it be possible to provide map of what happens when drivers / riders check different boxes? It would be good to review to add some clarity to the signup form and potentially refine the process.
