### ISSUE TITLE
Change main Tweet button text

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#154]
Support #Democracy4All this #Election2016. Sign up on CarpoolVote.com-Linking volunteer drivers & voters needing a ride @CarpoolVote

**Comment by moinshaikh** [comment]
I am ready to take this up. Pls. confirm if this is available.

Thanks!,
Moin

**Comment by sasjkia** [comment]
@moinshaikh great stuff! Please do! :)

**Comment by richardwestenra** [comment]
@sasjkia @moinshaikh Please note that the page URL is automatically added at the end of the tweet, so this message is too long. I recommend the following:
> Support #Democracy4All this #Election2016. Sign up on @CarpoolVote: Linking drivers with voters needing a ride

**Comment by sasjkia** [comment]
@richardwestenra thanks for spotting. that works.

**Comment by moinshaikh** [comment]
cool. noted.
