### ISSUE TITLE
Add terms and conditions

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#161]
Use terms and conditions in the following document: https://docs.google.com/document/d/1ouu7DBSgAP2RBK93hnHX0YIY45oVopyxVriEtrE3KYA/edit?usp=sharing
- [x] Create a separate page that contains the terms and conditions
- [x] Create a link in the bottom-right of the footer on the home page that links to the Terms and Conditions
- [x] On the DRIVER and RIDER signup forms, add statement with check box: "I agree to the Terms and Conditions", right above "We'd like to keep you updated..." Checkbox.
  Underneath this statement, include - as part of the same single check box but in three separate paragraphs - the three statements that were previously three separate checkboxes ("I understand that Carpool Vote will share my contact details...", "I understand that Carpool Vote provides introductions between riders...", "I understand that this service is open to any driver or rider...").
  Underneath these paragraphs, add a link to the Terms and Conditions page.
- [x] Change all mentions of "Carpool Vote" in the T&C's to "Carpool Vote LLC".

**Comment by moinshaikh** [comment]
Consider this taken by me :) Will try to do this ASAP.

**Comment by richardwestenra** [comment]
The third point in this issue isn't done yet.

**Comment by sasjkia** [comment]
Now that we have legal status, could we also add LLC behind all mentions of Carpool Vote?

Thanks!

**Comment by moinshaikh** [comment]
I have added replaced all mentions of 'Carpool Vote' with 'Carpool Vote LLC' in the T&C paragraphs. Pls advise if we need to replace this all over the page. (in meta title, tweet text, image alt tag etc.)
