### ISSUE TITLE
Usability feedback from a random user

### ISSUE THREAD

**Issue by dmilet** [voteamerica/voteamerica.github.io#163]
So I sent the url to the test environment to a colleague of mine, just asking her to sign up for a ride, and she got stuck after clicking on Virginia (under Find your polling place). She found the address of her polling station, and wondered what she was supposed to do next. It did not occur to her that she had left our site, now on Virginia Dept of Elections site. She was using her smartphone.
I had to tell her to find back the tab with our page, and enter the zip codes there. 
Demographics : she's a 20-something, college-educated Asian female living in Virginia, and a registered voter.

I wonder if the "find your polling place" will confuse more people than it will help.

**Comment by sasjkia** [comment]
@dmilet we need to think about this. Polling location checker is very useful but it's true that it takes people away from the site (even if it does open a new tab).

Is there a way to retain the benefits of the checker without the confusion?

**Comment by richardwestenra** [comment]
Great point. Maybe we could include a note saying that it will open a new website in a new tab?

**Comment by sasjkia** [comment]
@richardwestenra agreed.

Let's use the following working underneath Polling place heading:
"Link will take you to the Department of State website."

**Comment by pavsaiprasad** [comment]
Will take this one.

**Comment by dmilet** [comment]
It is not the Department of State web site, it is the State website with election information.

The Department of State is something else.

**Comment by sasjkia** [comment]
@dmilet fair point. this sometimes appears on DoS site of relevant state but not always.

@pavsaiprasad feel free to chance "Department of State" to just "State".

Thanks!

**Comment by pavsaiprasad** [comment]
@richardwestenra @dmilet @sasjkia - is a similar note also required for the "Am I registered?" polling place selection?

**Comment by sasjkia** [comment]
@pavsaiprasad good suggestion! yes - pls add.

**Comment by richardwestenra** [comment]
@sasjkia I've mentioned this to @pavsaiprasad in private on Slack, but just for visibility: 
We need to emphasise that this opens a different website in a new tab, because that’s the real usability issue here. I recommend the following wording:
> (Link will open your state’s polling place checker in a new tab.)
That okay with you?
