### ISSUE TITLE
Form can be submitted without insurance confirmation in DRIVER form

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#168]
I managed to submit a form without checking the insurance confirmation box. This should be required for a driver to be able to submit

**Comment by rahulteja16** [comment]
Hi. I will take this up. please assign this to me.

**Comment by richardwestenra** [comment]
@rahulteja16 Argh sorry I just completed this in #174, in which I'm already addressing optional/required fields!
