### ISSUE TITLE
Eliminate lower matches from the same driver in match notification

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#169]
Drivers can be matched multiple times with the same driver, since we're evaluating all time intervals given by the driver and rider.

Currently, they're sorted by score in the driver match notification emails. I would be better to eliminate the lower scores - and thus duplicates of the same rider - in these notification messages.

**Comment by dmilet** [comment]
Fixed fix candidate on /test environment. Did not clean up existing records though, so please try with new entries.

**Comment by sasjkia** [comment]
Am I right in thinking that this has been solved?

**Comment by dmilet** [comment]
Yes, it is no longer an issue. Please retest and close

**Comment by sasjkia** [comment]
Confirmed - thanks! :)
