### ISSUE TITLE
Expose Dates for Unmatched Rider/Drivers in API

### ISSUE THREAD

**Issue by langdonms** [voteamerica/voteamerica.github.io#171]
@sasjkia  has requested to be able to view the dates needed for unmatched riders/drivers as a pop-up event on the map. This requires them to be exposed in the JSON response from https://api.carpoolvote.com/live/unmatched-drivers and https://api.carpoolvote.com/live/unmatched-riders @dmilet how difficult would it be to implement this change?

**Comment by dmilet** [comment]
@sasjkia @langdonms 
I am concerned about the volume of data we would be extracting out of the system, and the cost (in CPU cycles and database i/o operations) that those would require, competing for the same resources that are used by the matching algorithm.
We have no idea of the uptake of the service. We have no idea how the matching behaves under stress.

Reporting is normally supported by a dedicated read-only database server, so as not to impact the core functions (for us, matching and user entry)

I would not recommend introducing additional real-time data reporting at this point.

**Comment by richardwestenra** [comment]
@dmilet @langdonms Closing this issue, but please let me know if you think it should be reopened.
