### ISSUE TITLE
Limit date and time selections for sign-up forms by state - MAIN BRANCH AND DEVELOP BRANCH

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#18]
This issue should be done AFTER #19 

In the I NEED A RIDE form, move Date and Approx Time selections to underneath the location information
In the I CAN OFFER A RIDE form, move Date and Approx Time selections to underneath the location information

Change "State" wording to:
RIDERS: In which state will you be voting?
DRIVERS: In which state will you be driving?

This is so that we can limit the dates and times available to early voting periods, based on the state selected.

Please limit the dates available to be selected for each state selected based on the early voting dates, which can be found here: https://www.vote.org/early-voting-calendar/

Please limit the times available to be selected for each state selected based on polling location opening times for each state, which can be found here: https://ballotpedia.org/State_Poll_Opening_and_Closing_Times_(2016)

**Comment by misteranderson** [comment]
Do we actually want to restrict the calendar of available dates; what if the rider needs a ride to get an ID?  What if the user can be picked up prior to poll opening time, to be there when polls open?

**Comment by sasjkia** [comment]
This is fair and I have been grappling with it. We don't want people to be signing up in pointless ways...

Perhaps a solution would be to add the option to check/display early voting dates and and polling times for their states.
