### ISSUE TITLE
DRIVER email entry must be mandatory

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#183]
Email entry can be optional for riders (who may only have phone access) but drivers need to provide this to receive notifications (we do not currently have sms activated).

**Comment by pavsaiprasad** [comment]
picking this up

**Comment by moinshaikh** [comment]
This is taken and done :) @pavsaiprasad

**Comment by sasjkia** [comment]
ok, we need to come back to this:

SMS notifications don't contain all of the driver offer management links. Emails do. The self-service portal currently doesn't support individual match cancellation and doesn't contain responses for other button actions, in a way that lets the user understand what just happened.

as an interim fix, please can we make driver email mandatory asap?

thanks!
