### ISSUE TITLE
Driver was able to submit form without date/time information

### ISSUE THREAD

**Issue by dmilet** [voteamerica/voteamerica.github.io#184]
Can we prevent this from the form, or I'll have to enforce it at DB level, but this will result in an error which will need to be handled by the UI.

**Comment by dmilet** [comment]
@sasjkia do you want to contact this driver and ask for her time availability  ?

carpool_v2.0_live=> select "DriverFirstName", "DriverLastName", "DriverEmail", "DriverCollectionZIP", "DriverPhone", state_info from stage.websubmission_driver where state='Failed';
 DriverFirstName | DriverLastName |        DriverEmail        | DriverCollectionZIP | DriverPhone |         state_info
-----------------+----------------+---------------------------+---------------------+-------------+-----------------------------
 Mary            | Filer          | momwhoneedsanap@gmail.com | 24019               | 5409154013  | Invalid AvailableDriveTimes

**Comment by sasjkia** [comment]
will do

**Comment by sasjkia** [comment]
done

**Comment by jkbits1** [comment]
@richardwestenra this was prevented by the form (using a fix you made recently) for the old date picker. Is  a new test needed for the latest one?

**Comment by dmilet** [comment]
Another instance of the same issue
 d1af356a-48d7-4a7c-a3a6-7b08a89cabd8 | 73.229.216.26 | Kevin          | Bell          | relay2-me@comcast..net | 303-317-6530 | 80010              | 80011           |
                   |              1 | t                | t                 | t                        | t                 | f              | Email                 | I do n
ot use walkers, dogs or any other external device that would require any special accomodation. | t                 | t            | Failed | 2016-10-26 22:23:59.468059 | 2
016-10-26 22:24:15.449378 | Invalid AvailableRideTimes | t               |

**Comment by richardwestenra** [comment]
@jkbits1 It should be picked up by the validator. I'm not sure why this one wasn't, but we can do some testing to figure it out. It's most likely someone using [desktop Safari, Firefox or IE](http://caniuse.com/#feat=input-datetime).

@dmilet Can you please be very very careful about posting users' private details on GitHub? This is a very public forum. I've edited your message to remove the phone number and email address.

**Comment by pavsaiprasad** [comment]
looking into this...

**Comment by sasjkia** [comment]
Closing this issue because I tested and am unable to submit without proper information. Let me know if I'm missing something.
