### ISSUE TITLE
No submit button on the self-service page

### ISSUE THREAD

**Issue by dmilet** [voteamerica/voteamerica.github.io#185]
hey, just got the below message. what's the status of self-service?
"Good morning:

I signed up last night, but when I click the link to manage my rides, I enter my info, but there is no button to click to send it through.

Please advise.

Thanks.

Suzanne"

**Comment by dmilet** [comment]
I tried it from my iPhone, there is indeed no button. 
The parameter name in the URL is wrong too, needs to be changed to uuid_driver, that is driven by the node app.

**Comment by jkbits1** [comment]
@dmilet the buttons are not shown if the self service page is not provided with a valid uuid (with the correct parameter name)

**Comment by richardwestenra** [comment]
As discussed on Slack:

> At present, when you submit the form, it adds a `uuid` query string key to your URL. However it looks like the form needs the qs keys `UUID_driver` or `UUID_rider`. I think I’ll change it on the front-end link so that it adds a `type` QS key. (e.g. `type=rider` or `type=driver`). Then I can populate the link from the thanks page.
> We’ll probably need to add an input field for the UUID reference on the form, if users don’t have the UUID already added to their URL .
> I’ll also add radio buttons for ‘[ ] I need a ride / [ ] I am offering a ride’. 

I’ll take this and start on this today/tonight.

**Comment by jkbits1** [comment]
@richardwestenra it's possible we have two issues overlapping here. 1) the node app redirects the browser after a successful driver/rider insert. that redirect is to the thanks page (link provided by the client), currently with a uuid 2) the self-service page requires the UUID_driver and UUID_rider. these are mainly provided by the email/sms links. it's possible they are created by the thanks page, if that links to the self service page

**Comment by langdonms** [comment]
Also not seeing a submit button, but created rider/diver from @richardwestenra 's test site. Is self-service available for test users?
