### ISSUE TITLE
User was able to submit invalid e-mail address

### ISSUE THREAD

**Issue by dmilet** [voteamerica/voteamerica.github.io#186]
This emailaddress@comcast..net  is invalid. It then fails sending notification e-mails
 d1af356a-48d7-4a7c-a3a6-7b08a89cabd8 | Bell          | 1234567890  | emailaddress@comcast..net                  | Failed         | 2016-10-26 22:23:59.468059 | 2016-10-26 22:24:15.449378 | 80010              | 80011           |              1 | t                 | f              |                       |

**Comment by misteranderson** [comment]
So, drop it and move on.  The only way you know for sure that an email address is valid is to send and email to it and have the recipient take some action.

As an aside, since this project is public, we should be cautious about including private info in problem reports.

**Comment by dmilet** [comment]
@sasjkia @jkbits1 @richardwestenra 
Yes that is what I am going to do on the back end.
I just want to be sure this is what we want as behaviour. An invalid e-mail means no notifications at all. Radio silence.

**Comment by richardwestenra** [comment]
+1 everything that @misteranderson said. I've edited the original message to remove personally-identifying information.
