### ISSUE TITLE
404 error on "email us" link on 'contributing.md' page.

### ISSUE THREAD

**Issue by moinshaikh** [voteamerica/voteamerica.github.io#188]
The link on the phrase "email us" under the 'contributing.md' page leads nowhere and throws a 404 error.
The faulty link is: https://github.com/voteamerica/voteamerica.github.io/blob/master/docs/slack@carpoolvote.com

![email 404](https://cloud.githubusercontent.com/assets/7282553/19773596/ce051e02-9c87-11e6-9aa2-38204e2e3af3.png)

![email error](https://cloud.githubusercontent.com/assets/7282553/19773673/1c7d28a4-9c88-11e6-8ed2-ea4b7f23bb09.png)

Can someone re-check and fix this.

Thanks

**Comment by richardwestenra** [comment]
This should link to `mailto:slack@carpoolvote.com`. My bad.

**Comment by richardwestenra** [comment]
Fixed in #193
