### ISSUE TITLE
Create FAQs

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#191]
These will free time spent responding to the same email questions and provide driver, riders, and partners with the basic info they need to use the platform:

https://docs.google.com/document/d/1Tf4jDAWSyqvBrSYxjFtTa_gjJrZ3Ti3b7tZlujQbGgY/edit?usp=sharing
- [x] Create a page dedicated to FAQs.
- [ ] Include a link to these right above the Terms and conditions in the footer (in the same format). Also include.
- [ ] Include another link to these on the "How does it work?" page, once its live.

**Comment by pavsaiprasad** [comment]
@richardwestenra @Carmenego - Probably better for Moin's PR on T&C and "How it works" to be merged into master, before getting this started.
