### ISSUE TITLE
Rearrange boxes on home page

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#192]
- [ ] Move ELECTION COUNTDOWN box to underneath MAP box.
- [ ] Move HOW TO CLAIM YOUR VOTE and VOTING SUPPORT boxes to home right underneath OUR STORY box.
- [ ] Move CAN I HELP IN SOME OTHER WAY to underneath ELECTION COUNTDOWN box.

**Comment by richardwestenra** [comment]
To whoever takes this task: Please bear in mind how this will look on mobile in single-column view, and be aware that we don't have complete control over where everything gets placed.
