### ISSUE TITLE
Rider cancelled ride request text

### ISSUE THREAD

**Issue by Carmenego** [voteamerica/voteamerica.github.io#195]
![image](https://cloud.githubusercontent.com/assets/23081790/19829850/92488d2e-9de3-11e6-80b2-7e90bc22dbc3.png)

My test rider account was matched up with someone, so I cancelled the ride request to stop it from happening again and got the following email. Clicking on "cancel ride request" generated the screenshot above.

> Dear Carmen DCrider,
> Great news - a driver has accepted your request for a ride!
> M**\* K**\* will get in touch to arrange the details of the ride.
> If you DO NOT hear from M***, please feel free to reach out :
> - (_)Email: mk_**@gmail.com
> - (*)Phone: [phone]
> - SMS/Text: [phone](*) = Preferred Method
>   If you would prefer to have a different driver, please let us know, and cancel this ride match only
>   To view or manage your matches, visit our Self-Service Portal
>   If you no longer need a ride, you please cancel this Ride Request
>   Warm wishes
>   The CarpoolVote.com team.

**Comment by jkbits1** [comment]
@Carmenego great testing :+1:
