### ISSUE TITLE
Rider request perhaps too easy to cancel

### ISSUE THREAD

**Issue by langdonms** [voteamerica/voteamerica.github.io#199]
SMS confirmation from signup of my my test rider has a direct link to cancel the request. This can be easily accidentally clicked on phones resulting in a canceled ride. 

From CarpoolVote.com\nRide Request received! Ref: ab94c6c9-b614-424d-b594-c17548ec59d4\nPreferred Ride Times : 2016/10/31 09:00-2016/10/31 22:00\nPick-up location : 30328\nDestination : 30328\nParty Size : 1\nWheelchair accessibility needed : Yes\nTwo-way trip needed : Yes\nNotes : test note\nPhone Number : 9374088508\nSelf-Service portal : **http://carpoolvote.com/self-service/?uuid_rider=ab94c6c9-b614-424d-b594-c17548ec59d4\nCancel : https://api.carpoolvote.com/test/cancel-ride-request?UUID=ab94c6c9-b614-424d-b594-c17548ec59d4&RiderPhone=Sandersridertest**

**Comment by richardwestenra** [comment]
Closing this issue because
1. The SMS confirmations are generated on the back end, not the front end.
2. The election is over.

It'll be worth bearing this in mind for the next iteration though. Cheers @langdonms!
