### ISSUE TITLE
Add legal tick boxes to I NEED A RIDE form

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#20]
Please add the following to the end of the I NEED A RIDE form

꧐ I understand that Carpool Vote will to share my contact details with the driver if there’s a match. We will not share your details with anybody else.
Hover text: Your details are safe with us! We’ll only share them with officials if they need them for a safety-related matter, and will destroy them within three months of Election Day.

꧐ I understand that this service is open to any driver or rider - no matter what their personal background or beliefs. To help make sure that both the driver and I feel comfortable and safe, I promise that I will not discuss politics during the journey.

**Comment by sasjkia** [comment]
Thanks very much for doing this! Thinking about it, hover text is not very practical for mobile. Could we pls change to the below?

I understand that Carpool Vote will share my contact details with the driver if there’s a match. (Carpool Vote will not share personal details with anybody else, unless required by law, and will destroy them within three months of election day.)

**Comment by GregSaintJean** [comment]
https://github.com/voteamerica/voteamerica.github.io/pull/24
