### ISSUE TITLE
Driver confirmation page tweet appears to be for riders

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#202]
Haven't tested the other way around

**Comment by moinshaikh** [comment]
I tested them both, both page tweet appears to be same:

Driver confirmation page:
(http://carpoolvote.com/thanks-driver/?uuid=6a69e467-8181-4e91-aef4-ccaa847cba4e)

I’ve signed up for a ride to #ClaimMyVote on @CarpoolVote. #Election2016 will be close. #CountEveryVote http://carpoolvote.com/thanks-driver/?uuid=6a69e467-8181-4e91-aef4-ccaa847cba4e


Rider confirmation page:
(http://carpoolvote.com/thanks-rider/?uuid=f088f994-c358-4c2d-89ca-3b54e7f880ef)

I’ve signed up for a ride to #ClaimMyVote on @CarpoolVote. #Election2016 will be close. #CountEveryVote http://carpoolvote.com/thanks-rider/?uuid=f088f994-c358-4c2d-89ca-3b54e7f880ef

**Comment by moinshaikh** [comment]
Can you advise the correct/new text for tweet for Rider page, I can help here.

**Comment by misteranderson** [comment]
The important thing is -not- to link the tweet to the self service page -
those urls have an identifier which should not be made public.

-- Eric

**Comment by moinshaikh** [comment]
I was about to share this exact opinion @misteranderson 

We can just have text and at most, link to home page.

**Comment by misteranderson** [comment]
I have merged this; I have another PR #206, which is also affecting the tweeting.  I have checked the new tweet text and it's now different for drivers.
