### ISSUE TITLE
Add customer service phone number to the home page

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#203]
- [ ] Move the phone number text in the "Need voter support" banner at the top to the left of the banner.
- [ ] To the right of the banner, add "For help using Carpool Vote, call or SMS: 804-239-3389".

**Comment by pavsaiprasad** [comment]
@sasjkia - should this perhaps be "Call 1-866-OURVOTE for Voter Support. For help using Carpool Vote, call or SMS: 804-239-3389", because adding Call 1-866-OURVOTE to the left of the banner doesn't sit well with the existing text of "Need voter support?".

**Comment by sasjkia** [comment]
@pavsaiprasad good point - thanks for flagging!

Yes, happy with your suggestion. Please go ahead.

**Comment by richardwestenra** [comment]
@sasjkia Should this be applied to all the other pages, or just the homepage?

Also, did you intend for the text to be broken into two sections (one left aligned, one right aligned) or just one line along the top bar?

**Comment by sasjkia** [comment]
@richardwestenra thanks for spotting! yes -pls all pages. i think it may be easier to read if text was broken into 2 sections. thanks!
