### ISSUE TITLE
Add legal tick boxes to I CAN OFFER A RIDE form

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#21]
Please add the following tick boxes to the bottom of the I CAN OFFER A RIDE form

꧐ I understand that Carpool Vote will share my contact details with the rider if there’s a match. (Carpool Vote will not share personal details with anybody else, unless required by law, and will destroy them within three months of election day.)

꧐ I understand that this service is open to any driver or rider - no matter what their personal background or beliefs. To help make sure that both the rider and I feel comfortable and safe, I promise that I will not discuss politics during the journey.

Please add the following form underneath the insurance tick box in the I CAN OFFER A RIDE FORM

Driver license number ______________________
For safety reasons, we keep a record of all drivers' license details. If the ride is completed safely, we will not share this information with anybody else, and will destroy it within three months of election day.

**Comment by GregSaintJean** [comment]
Can you give me an idea of how you want the hover text to look like?

**Comment by sasjkia** [comment]
Good point - I've updated the wording.

Also changed vehicles registration to license - upon a partner's suggestion.

**Comment by GregSaintJean** [comment]
O no. Lol! I'll do another pull request.
