### ISSUE TITLE
Change notes box text for RIDER signup form

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#211]
Some states require child seats by law. Some orgs want drivers to collect voting assistants from different locations. Some want drivers to prioritize riders from their own org. SO... with all of this in mind, please could we notes box text in RIDER signup form to the following?

"Accommodation requirements e.g. service animal, assistance folding equipment, assistance entering/exiting the vehicle, child car seat or booster (please include age), must also collect non-voting assistant or companion, or anything else the driver should know."

**Comment by gavinkalika** [comment]
created pull request

https://github.com/voteamerica/voteamerica.github.io/pull/217

Any comments or concerns please post them

**Comment by gavinkalika** [comment]
how to close issue? solution is merged into master

**Comment by richardwestenra** [comment]
@gavinkalika Ah thanks for the heads up, I missed this! Closing now.

btw if you include the words "Fixes #XXX" (where XXX is the issue number) in your [commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) or [PR description](https://github.com/blog/1506-closing-issues-via-pull-requests) then GitHub will automatically close the issue for you.
