### ISSUE TITLE
Failed Driver records because of Invalid Drive Times

### ISSUE THREAD

**Issue by dmilet** [voteamerica/voteamerica.github.io#214]
There are 2 types of failures which I believe should be caught by the the form
1. drive times is empty 
2. End time is before start time

carpool_v2.0_live=# select state_info, "UUID", last_updated_ts, "AvailableDriveTimesLocal"  from stage.websubmission_driver where state='Failed';
                               state_info                               |                 UUID                 |      last_updated_ts       |
                 AvailableDriveTimesLocal
------------------------------------------------------------------------+--------------------------------------+----------------------------+----------------------
---------------------------------------------------------------------------------
 Invalid AvailableDriveTimes                                            | 3b3aad19-5394-44df-8e0a-d1092f4c0052 | 2016-10-29 20:43:01.506209 |
 Invalid AvailableDriveTimes                                            | 104fbd6f-2ee9-4bf7-9279-74e9d66ea31f | 2016-10-30 16:34:08.09577  |
 Invalid/Not Found DriverCollectionZIP:27600                            | 174cddc2-b619-4373-9e3a-98e78a7850b0 | 2016-10-30 20:35:48.491253 | 2016-11-04T14:00/2016
-11-04T18:00|2016-11-05T09:00/2016-11-05T11:00
 Invalid AvailableDriveTimes                                            | a5f5fcfe-bdae-4278-af97-886edb8279c5 | 2016-10-31 18:56:17.684955 |
 Invalid AvailableDriveTimes                                            | 3f488908-6bd0-4304-b126-99ebfa5a3f7d | 2016-10-31 23:47:20.720837 |
 Invalid AvailableDriveTimes                                            | d4241fa7-efac-42c5-9491-6c7af21ceb9b | 2016-11-01 16:38:19.030921 |
 Invalid value in AvailableDriveTimes:2016-11-04T22:00/2016-11-04T14:00 | 755ec17b-2f0e-4592-a5cc-5b2d223b5e6a | 2016-11-03 16:01:55.376477 | 2016-11-05T07:00/2016
-11-05T15:00|2016-11-04T22:00/2016-11-04T14:00|2016-11-08T07:00/2016-11-08T17:00
 Invalid AvailableDriveTimes                                            | c34f680e-ec00-48ae-9db5-5a4b97158e61 | 2016-11-04 00:58:14.904566 |
 Invalid AvailableDriveTimes                                            | de8a5e45-b8c7-4dfd-91f9-ce4b1dfe668f | 2016-11-04 05:20:24.090202 |

**Comment by pavsaiprasad** [comment]
@dmilet @richardwestenra - the empty date field has been picked up as a part of #184 which is now in a PR.

**Comment by sasjkia** [comment]
Looks like this has been solved
