### ISSUE TITLE
Create more intuitive responses to email links

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#228]
currently, people receive the following format when they click a link. many are finding this confusing and are unsure whether or not they have taken action

![image](https://cloud.githubusercontent.com/assets/19363959/20062488/eb9a0b2e-a4d1-11e6-9ab0-78199097d63e.png)

Can we replace the responses with some basic text?
**Driver email links:**
- [ ] Accept match: Thank you for accepting this ride request! You have now been assigned to the rider. Please contact them to finalize the details of the ride.
- [ ] Cancel this drive offer: Your ride offer has been canceled. This cancellation includes all of your confirmed matches, if any. If you have already made plans to meet a rider, please contact them to let them know.
- [ ] Cancel this ride match only: Your ride match has been canceled. If you have already made plans to meet a rider, please contact them to let them know. This does not affect any of your existing matches.

**Rider email links**
- [ ] Cancel this request: Your ride request has been canceled. You will no longer be matched with a driver. If you already had a confirmed a match, this has also been canceled. If you still want to receive a ride, please sign up again or CarpoolVote.com or by calling 804-239-3389
- [ ] Cancel this ride match only: Your current ride match has been canceled. You will now have to wait to see if there's another match.

Could this text also be reflected in the self-service portal?

For the self-service portal, could the text for the buttons be changed to be a little clearer as to what they mean?

Driver self-service buttons:
- [ ] Cancel drive offer request > Change to "Cancel drive offer"
- [ ] Pause driver match request > Change to "Pause notifications"
- [ ] Cancel drive match request: If this doesn't work, we should not display it
- [ ] Accept driver match offer: The one at the bottom is additional to those that appear next to the actual matches. We need the ones next to the matches so people can accept them. It doesn't make sense to display the one at the bottom.

**Comment by richardwestenra** [comment]
@sasjkia Sorry, unfortunately I can’t do anything about that from here.
I just clicked the link and got this URL: https://api.carpoolvote.com/test/cancel-ride-request?UUID=06f24c19-4be4-4d20-950a-78f23c24d920&RiderPhone=Westenra

If you see the URL, it starts with api. Those pages are actually on the backend site. I created an issue about this over there 11 days ago: https://github.com/voteamerica/backend/issues/75

I'm not sure how to fix this issue myself :(
