### ISSUE TITLE
typo in FAQs

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#232]
NEEDS TO READ:

I need to change the details of my signup. How can I do this?

For drivers, the easiest way to change the details of your signup is to pause (NOT cancel) notifications for your current ride offer or request, then sign up again using the same details.

This will preserve any matches you've already accepted, while new notifications will have the updated details. I you do not yet have any confirmed matches, you can also cancel your offer.

For riders, the easiest way to change details is to cancel your request. If you do not have internet access, you can also call or SMS 804-239-3389, quoting your reference number, and we’ll try do this for you.

**Please also move the last question up to underneath "What happens if I cancel my current ride offer of request?"**

**Comment by jsms90** [comment]
@sasjkia I take it that you just want "Simply click the" removed from the beginning, and otherwise the text is fine?

**Comment by sasjkia** [comment]
@jsms90 i spotted the typo at the beginnig but didn't check the rest of the text.

**Comment by jsms90** [comment]
@sasjkia The rest looks identical :+1: 
Submitting a PR now
