### ISSUE TITLE
Should FAQ answers have anchor tag/link to "Go to Top"? section

### ISSUE THREAD

**Issue by moinshaikh** [voteamerica/voteamerica.github.io#241]
Hey guys,

do you think answers on faq page (http://carpoolvote.com/faq/) should have an anchor tag/ 'Go to top' link that allow reader to go to top section (the list of questions or question header section)

something like this:

![go to top](https://cloud.githubusercontent.com/assets/7282553/20098482/1057a738-a5da-11e6-9893-92c06aacaff9.png)

**Comment by richardwestenra** [comment]
Hey @moinshaikh, thanks for the suggestion! It's not a bad idea, but I'd say it's probably unnecessary. Scrolling is easy, and by not including these links we avoid distractibng users with unnecessary visual complexity.
