### ISSUE TITLE
Create Values page and working together guidelines in Github Documents folder

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#253]
**Note: This task is suitable for a beginner developer, especially for someone wanting to make their first PR. We are leaving it here for a beginner to take on. Thanks! 🙂**

# Task Description

Please use the contents from the below Google Docs to create 2 separate markdown readme documents, and add them to the [/docs](../tree/master/docs) folder:

- [Brand Values](https://docs.google.com/document/d/1Ny4wTBFaqWLTGpYUgZMAsdrp6gNv3CsB_Bu8xGEYELk/) --> /docs/values.md
- [Working Together](https://docs.google.com/document/d/1wgVty_YEzGEEd2yAmUqjah7ZgNuXyH8xyXbvWZnlWHc/) --> /docs/working-together.md

Please ensure that you maintain appropriate syntactical formatting. You'll need to convert the RTF-formatted text to markdown. Try googling for an automatic converter.

Then please add a link to each of these documents in the main readme - maybe in the [Contributing section](https://github.com/voteamerica/voteamerica.github.io#contributing)? Ask @richardwestenra if you need help with the wording.

**Comment by AyahRamahi** [comment]
Hi, I am a beginner . How can I help in this ?

**Comment by jkbits1** [comment]
@AyahRamahi thanks for offering to contribute 👍 you can certainly help with this issue.

Another contributor created the two documents mentioned above, but we don't have links to them on the https://github.com/voteamerica/voteamerica.github.io/blob/master/docs/contributing.md page. The documents weren't there if you looked before, I've only just merged that PR.

Could you add links to these documents there on the contributing page, please? You could put the links at the bottom of the `Philosophy` section.

You could also make some useful changes to the working together page:
https://github.com/voteamerica/voteamerica.github.io/blob/master/docs/working-together.md

Above the section about Agile Project Management, it would be useful to add a brief new section above the words `Moving forward, we would like ...` (that's about the sixth paragraph). A new heading `Current Status` with the text `We are working together with Slack, please join us using the link on the contributing page`.

If that text is followed by a second new heading, `Future Plans`, that will best describe how we are working together right now.

Does all sound possible? Please feel free to ask any questions you have 🙂

**Comment by AyahRamahi** [comment]
@jkbits1 I think i can do this. If I face problems I will comment it here. Thank you.

**Comment by jkbits1** [comment]
@AyahRamahi thanks for the useful questions 👍 1) that's a very good point about the links. Perhaps `Here is some more information about our values`, where `our values` is the link, and `Learn more about how we work together`, where `how we work together` is the link, would give readers some context. Feel free to amend any of that text if you think it needs improvement 2) I think if the Future Plans heading is before the text `Moving forward, we would like`, that describes our current situation best. At the moment we are not using Agile or, at least, not in a formal way. Again, if you think you can improve the text, go ahead.

You are very welcome to join the Slack channel at any time 🙂 to discuss this issue, the project in general or anything else. We are a diverse and friendly team and any interest and thoughts are welcome. We are located across various time zones so we may be slow to reply, but will do so!

**Comment by jkbits1** [comment]
Fixed by #361 #373 #374 thanks to those contributors 👍 🙂
