### ISSUE TITLE
Update site text etc to be relevant to new year

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#254]
**Update signup forms**
- [x] On both signup forms, make dates available for current year
- [x] On both signup forms, ensure that start times and end times are mandatory fields
- [x] On driver signup form, change "Seats available in vehicle" to "Passenger seats available in vehicle"
- [x] On driver signup form, change "Driver's licence number" to "Vehicle licence plate number"
- [x] On both signup forms, change", and will destroy them within three months of election day" to ", and will destroy them within three months of election day of you've asked us not to stay in touch."
- [x] On rider signup form, add the following as the penultimate point under the Terms and Conditions summary: "I understand that Carpool Vote cannot guarantee that I will find ride by using the platform, or that a driver will provide a ride as agreed. I will keep looking for a ride until I have reached my destination."
- [x] On the driver signup form, add the following as the penultimate point under the Terms and Conditions summary: "I understand that Carpool Vote cannot guarantee that I will find appropriate matches through the platform, or that any agreed ride will occur. I take full responsibility for any cost related to using the platform."
- [x] On rider signup form, change "Preferred method of contact" to "Preferred method of contact from driver (choose as many as you like). If you select a cell phone, we'll also send you text message updates."
- [x] On rider signup form, underneath phone number box, add question "Is this a cell phone?" with yes/no check box
- [x] On driver signup form, change "Preferred method of contact" to "Preferred notification method (choose as many as you like)"; remove "Phone" as an option.
- [x] On driver signup form, change "Phone number (cell preferred)" to "Cell phone number"
- [x] On the driver signup form in the notes page, create a separate bullet point for each type of accommodation needed. After car seat requirements, add "- Can only communicate in a language other than English"
- [ ] ~On both signup forms, improve the contrast of the explanatory text in boxes. Currently, it's grey, which makes it difficult to read for people with vision difficulties.~ [Note: to be discussed. Ignore this for now. - @richardwestenra]

- [ ] Add LLC after Carpool Vote only on the Terms and Conditions page: http://carpoolvote.com/terms-conditions/

**Update "OUR STORY" page**
- [x] At the beginning, add a paragraph: "Carpool Vote launched in 2016 to fight back against voter suppression."
- [x] Change "The 2016 US Presidential election will be..." to
"The 2016 US Presidential election was the first since this change happened. Voter turnout was at a 20-year low.

People who used our service in 2016 faced several barriers to getting to the polls. These included: 
- Closure of polling places in lower-income communities of color. 
- Inaccessibly remote locations for would-be voters to get a photo ID to register. 
- Shrinking voter registration periods. 
- Prohibitive absentee ballot procedures.

These barriers - along with others introduced since the change - affected everybody but especially people of color, people with disabilities, young people, elderly people, and women.

In 2016, so few votes were cast that president Trump was elected by barely a quarter of Americans eligible to vote.

_Find out more about voter suppression_

There is currently little support in government to make it easier for people to access democracy. So, our mission continues for the 2017 Virginia and New Jersey state elections, and the 2018 midterms: to help make sure that no vote goes uncounted.

While we're at it..."

- [x] Make both of the links open in a new tab when clicked.

- [x] Delete election countdown clock

~**Update election countdown clock box**~
~(we could just delete it for now, if it's going to slow things down)~
- [ ] ~Change title to: 2017 VA AND NJ ELECTION COUNTDOWN.~
- [ ] ~Remove "270 to win" box from countdown clock.~
- [ ] ~Reset countdown clock, to count to November 7, 2017~
- [ ] ~On countdown clock, change "Presidential Election" to "State elections" and change date text to November 7.~
- [ ] ~Underneath the clock, add a link to 2017 SPECIAL ELECTIONS: https://ballotpedia.org/State_legislative_special_elections,_2017~

**Update tweet text**
The tweet at the top of the page refers to the 2016 election. Please change to: _Support #VotingRights in 2017 #USelections. Sign up via @CarpoolVote: Linking drivers with voters needing a ride. carpoolvote.com_

**Comment by sasjkia** [comment]
@jkbits1 @dmilet some of these relate to the back end.

**Comment by udupashreyas** [comment]
Hi, I was wondering if the seventh point in the checklist was incomplete or missing a few words. (Or, is the last phrase not to be added?)

**Comment by sasjkia** [comment]
@udupashreyas good spot - thank you! I've updated this now.

**Comment by geoffreyyip** [comment]
I'm assigning myself to this.

Note to self: sasjkia says hide the clock if you can't fix it.

**Comment by sasjkia** [comment]
thanks @geoffreyyip! Please also coordinate with the backend, as some of these changes will affect the database.

**Comment by geoffreyyip** [comment]
@sasjkia

Items 6-9 are in a pending pull request, so I skipped those. As for the rest, I need some clarifications. And I made some recommendations. Most important thing is that we need to make a new countdown widget.

> On the driver signup form in the notes page, create a separate bullet point for each type of accommodation needed. After car seat requirements, add "- Can only communicate in a language other than English

Rider Accomodation Notes is currently in [rider sign-up](http://carpoolvote.com/#need-ride), not [driver sign-up](http://carpoolvote.com/#offer-ride). How should I proceed?

> On both signup forms, improve the contrast of the explanatory text in boxes. Currently, it's grey, which makes it difficult to read for people with vision difficulties.

I'm not sure if we should do this. 

Semantics take priority over visuals. Better labels will solve this. Placeholder text should complement labels. Screen readers will work as long as a complementary label exists per form input. (Disclaimer: Not an accessibility expert.)

Changing the color would also violate convention. Users expect forms to look and work a certain way. A different color harms usability and that could mean a net loss for vision-impaired. (Again, not an expert.)

Besides, placeholder text (or "explanatory text in boxes") is hard to style. Implementation differs between browsers, and it could be hard to maintain it over time.

> Add LLC after Carpool Vote only on the Terms and Conditions page: [http://carpoolvote.com/terms-conditions/](http://carpoolvote.com/terms-conditions/)

Would you like the content added at the start, at the end, or in the middle? And should I add a section header for the LLC?

> Update "Our Story" Page

This part's easy. But you also need to change the content in the [front page story box](carpoolvote.com/#story). (Don't worry about how weird the layout looks when you click on the link. Normal people wouldn't come up with that url.) Right now, it says:

*In many states, new voting rules have made it more difficult for people to get to polling stations. These rules particularly affect people of color, people with disabilities, young people, elderly people, and women. Carpool Vote is a tool to fight back against an unfair political system in the 2016 election.*

*We connect volunteer drivers with anybody who needs a ride - to the polls or voter I.D. office.*

*[Read more](http://carpoolvote.com/story/)*

What do you want to change it to?

> Update election countdown clock box

This needs to be its own issue. Currently the website imports the countdown widget from a different website. All the values are fixed by that third-party. It's designed for just the 2016 election. We don't have access to the source code for that widget.

I recommend we code our own widget. (And by code our own widget, I mean find a library that does it for us.) That way, we can update the dates and content on our own later on.

**Comment by geoffreyyip** [comment]
P.S. To the best of my knowledge, none of these changes will affect the database.

**Comment by sasjkia** [comment]
> Rider Accomodation Notes is currently in rider sign-up, not driver sign-up. How should I proceed?
Good spot. This still applies to rider (not driver) form.

>I'm not sure if we should do this.
Thanks for this. This change was recommended by Tino (not all people with poor vision use screen readers) but, thinking about it, I agree. Let's leave it until some further UX discussions.

>Would you like the content added at the start, at the end, or in the middle? And should I add a section header for the LLC?
At first mention: 'Carpool Vote LLC ("Carpool Vote")'. Thereafter, just 'Carpool Vote'.

>This part's easy. But you also need to change the content in the front page story box. 
That's right; please can you just remove the reference to 2016? The rest should be fine.

>This needs to be its own issue.
Yes, let's think about a practical way to do this. Meanwhile in its place, can we add the dates for the NJ and VA primaries and main elections? Plus a link to the special elections date underneath.

UPCOMING ELECTIONS
New Jersey state primaries: June 6, 2017
Virginia state primaries: June 15, 2017

New Jersey and Virginia state elections: November 7

2017 special elections: https://ballotpedia.org/State_legislative_special_elections,_2017

**Comment by sasjkia** [comment]
@geoffreyyip i've also added updated tweet text, as this was referring to 2016 elections

**Comment by geoffreyyip** [comment]
Need two more things clarified:

>On the ~~driver~~ rider signup form in the notes page, create a separate bullet point for each type of accommodation needed. After car seat requirements, add "- Can only communicate in a language other than English"
When you say separate bullet points, do you mean separate checkboxes like the following?

- [ ] I am a powerchair user who needs an adapted van with a lift.
- [ ] I need a two-way trip.
- [ ] I am bringing a service animal
- [ ] I need a child car seat (please include age below)
- [ ] Other (please fill out textbox below)
{and then a text box, where user can fill in other info}

If so, please include the exact wording you're looking for. 

>Add LLC after Carpool Vote only on the Terms and Conditions page: http://carpoolvote.com/terms-conditions

So I'm adding the LLC disclaimers to the Terms and Conditions page. Should I also remove the LCC text from the driver and rider signup forms?

P.S. I made an edited version of your issue text so the items were numbered. When I'm done with the issues, I'll send the Markdown text over, so you can update the issue.

P.P.S. Regarding the twitter text, we have a bigger problem. Neither the Facebook or Twitter social buttons are visible. This needs to be a separate issue.

**Comment by sasjkia** [comment]
>When you say separate bullet points, do you mean separate checkboxes like the following?

No. Just exact same wording as it appears, but one after the other so it's easier to read.

> Should I also remove the LCC text from the driver and rider signup forms?

Yes pls. 

>Neither the Facebook or Twitter social buttons are visible in my browser.

Oh dear. What browser are you using. Can you create an issue pls?

**Comment by geoffreyyip** [comment]
- [ ]  On the rider signup form in the notes page, create a separate bullet point for each type of accommodation needed. After car seat requirements, add "- Can only communicate in a language other than English" 

This needs more discussion. You requested bullet points (or at least separate lines), but I think we can do better.

Currently, the accommodation notes are displayed as `placeholder` text. Check [here](http://carpoolvote.com/#need-ride) and search for Vehicle Requirements. `placeholder` attributes are meant for short hints. From the W3 HTML Spec:

> The `placeholder` attribute represents a *short* hint (a word or short phrase) intended to aid the user with data entry when the control has no value. A hint could be a sample value or a brief description of the expected format. The attribute, if specified, must have a value that contains no "LF" (U+000A) or "CR" (U+000D) characters.
>
> The `placeholder` attribute should not be used as a replacement for a `label`. For a longer hint or other advisory text, place the text next to the control.
>
> **Use of the `placeholder` attribute as a replacement for a `label` can reduce the accessibility and usability of the control for a range of users including older users and users with cognitive, mobility, fine motor skill or vision impairments. While the hint given by the control's `label` is shown at all times, the short hint given in the `placeholder` attribute is only shown before the user enters a value. Furthermore, `placeholder` text may be mistaken for a pre-filled value, and as commonly implemented the default color of the placeholder text provides insufficient contrast and the lack of a separate visible `label` reduces the size of the hit region available for setting focus on the control.**

Emphasis mine. The current `<textarea id="RiderAccommodationNotes">` element has this monstrosity:

> Accommodation requirements e.g. service animal, assistance folding equipment, assistance entering/exiting the vehicle, child car seat or booster (please include age), must also collect non-voting assistant or companion, or anything else the driver should know.

Even if we wanted to add bulletpoints or line breaks, it's hard to style placeholder text with any consistency. There are hacks to put the requirements on separate lines, but they're not consistent across browsers. The spec quote above mentions that placeholder text should not accept line break characters (or LF + CR):

> The attribute, if specified, must have a value that contains no "LF" (U+000A) or "CR" (U+000D) characters.

I recommend we redesign the rider accommodation form entirely. Rider accommodation forms should be more than two checkboxes and a generic `textarea` input.

- [ ] Add LLC after Carpool Vote only on the Terms and Conditions page: [http://carpoolvote.com/terms-conditions/](http://carpoolvote.com/terms-conditions/)

> > Should I also remove the LCC text from the driver and rider signup forms?
>
> Yes pls. Except the first time. No need to put anything in brackets after for the signup forms.

I'm on it.

- [ ] Update tweet text: The tweet at the top of the page refers to the 2016 election. Please change to: **Support #VotingRights in 2017 #USelections. Sign up via @carpoolvote: Linking drivers with voters needing a ride. carpoolvote.com**

> > Neither the Facebook or Twitter social buttons are visible in my browser.
>
> Oh dear. What browser are you using. Can you create an issue pls?

Yup, will do. It's on my todo list after I get all of this done.

**Comment by sasjkia** [comment]
@geoffreyyip thanks for this suggestion. This makes a lot of sense!

Check boxes are probably not the way; one freeform box is enough. What do you think of the idea of having a bulleted list next to the box, to use as reference?

As for the LLC, delete all except for the first mention, on both drivers and riders signup forms.

**Comment by geoffreyyip** [comment]
> Check boxes are probably not the way; one freeform box is enough. What do you think of the idea of having a bulleted list next to the box, to use as reference?

How does this work? Also, was this "I speak a language other than English" checkbox what you were thinking about?
![Vehicle Requirements Form](https://cloud.githubusercontent.com/assets/15312106/26071641/c92c380c-3976-11e7-9d44-d07276135e5f.png)

> As for the LLC, delete all except for the first mention, on both drivers and riders signup forms.

Still confused here. Do you mean shortening it from three paragraphs to one paragraph?

Three paragraphs:
![Old LLC Form](https://cloud.githubusercontent.com/assets/15312106/26071778/3a93bfb0-3977-11e7-9165-93bdf9699572.png)

One paragraph:
![New LLC Form](https://cloud.githubusercontent.com/assets/15312106/26071802/507a5bd6-3977-11e7-80cf-9f58fe84d6d6.png)

**Comment by richardwestenra** [comment]
Please note that @udupashreyas has taken care of points 6 through 9 in #272 (pending changes before merging).

**Comment by richardwestenra** [comment]
I've just caught up on recent comments on this thread. @geoffreyyip I support everything you've said on this issue, and I'm very pleased by your suggestions and your thoroughness. Thanks a lot for taking this on, and for showing concern for good UX design and a11y best practices! I really appreciate it.

Regarding the contrast of placeholder text: I agree. I think the placeholder text is as opaque as we can reasonably make it without it being confused for user input text. And as you mentioned, placeholder text should not be used for conveying crucial information. I've not been super happy with the massive placeholder on the 'Notes' textarea, but decided that this is supplementary information rather than crucial info, and that in the rare cases where users might miss it, it's not a big deal, so it's okay for it to be a placeholder. However I'm perfectly happy for this info to be placed in a note under the textarea instead.

btw Geoffrey I tried to assign you to this issue, but I'll be unable to do so until you are added as a collaborator. I've added you and sent you a request, but you need to accept the request before you can be assigned. Sorry :/

**Comment by geoffreyyip** [comment]
@richardwestenra I accepted the request. Please assign me as collaborator when convenient.

@sasjkia I am still awaiting clarification on LLC. Once that's done, I can submit the pull request.

**Comment by richardwestenra** [comment]
@geoffreyyip Done! Btw if you've got some work in progress, feel free to submit a PR and keep adding to it as you like. That way we can preview your work and check if you're on the right track, as well as helping ensure that we don't work on the same thing.
Just be sure to include a note in the description to let us know whether it's ready to merge, so it doesn't get merged before you're ready.

**Comment by sasjkia** [comment]
@geoffreyyip please keep the three paragraphs as and and add the fourth paragraph as outlined in this PR. the "LLC" (literally just those letters) should only appear on first mention.

**Comment by sasjkia** [comment]
@geoffreyyip actually, looks like @udupashreyas  has been working on this.

**Comment by geoffreyyip** [comment]
@sasjkia I think I get it now. On signup forms, the organization should be referred to as "Carpool Vote LLC" the first time, and "Carpool Vote' every time afterwards. On the Terms & Conditions, the organization should be referred to as "Carpool Vote LLC" all the time.

Wait, I thought @udupashreyas was working on tasks 6-9?

**Comment by geoffreyyip** [comment]
@richardwestenra Haha thanks. I've never submitted a pull request before. I'll get on that by early next week.

**Comment by sasjkia** [comment]
@geoffreyyip 
>  I think I get it now. On signup forms, the organization should be referred to as "Carpool Vote LLC" the first time, and "Carpool Vote' every time afterwards

Correct

> On the Terms & Conditions, the organization should be referred to as "Carpool Vote LLC" all the time.

No. On first mention, state 'Carpool Vote LLC ("Carpool Vote")'. then just 'Carpool Vote' thereafter.

Thank you!

**Comment by udupashreyas** [comment]
@geoffreyyip, yes, I was working on tasks 6 to 9

**Comment by richardwestenra** [comment]
@geoffreyyip Do you think we can get a PR submitted for this issue ASAP? There's no need to complete all the tasks in a single PR. In fact, better to break it up into several smaller PRs, than one big one.

In particular, we'd like to prioritise any tasks relating to removing any mention of 2016, including deleting the countdown click.

Can you please let me know which tasks you've completed, and which are free to be completed by others? I am somewhat free to help with this task but I've been holding back because I'm unsure which tasks you've already completed.

CC @sasjkia

**Comment by geoffreyyip** [comment]
@richardwestenra I just saw this message.

All items are completed (except for the LLC issue). I have to run right now, but I'll submit a pull request at about 10pm (or four hours from now).

**Comment by geoffreyyip** [comment]
@richardwestenra Event was postponed, so I got the pull request in a few hours early. Pull request is at #289.

Side note: I just realized that Pull Requests are created as Issues, and can be referenced using the same hashtag {#} shortcut. Mind blown.

**Comment by geoffreyyip** [comment]
Seems like we got all the items. Can we close this issue and move any remaining items to new issues?

**Comment by sasjkia** [comment]
Yes - thanks for persevering @geoffreyyip! Going forward, I'll keep the issues separate :)

**Comment by richardwestenra** [comment]
Belatedly closing this issue. Thanks @geoffreyyip, great work! 😄
