### ISSUE TITLE
Forms not redirecting to confirmation page after signup (#107 in backend)

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#263]
- [ ] Rider and driver signups no longer redirects to confirmation page after submission. Shows blank page with UUID instead.

- [ ] Ditto for confirmation page when driver has confirmed a match, rider has cancelled a match, etc

**Comment by sasjkia** [comment]
@richardwestenra @dmilet not sure if this is a frontend or backend issue?

**Comment by jkbits1** [comment]
@sasjkia thanks for details 👍 - this duplicates https://github.com/voteamerica/voteamerica.github.io/issues/257

**Comment by jkbits1** [comment]
@sasjkia this should be fixed by voteamerica/backend#104 and voteamerica/backend#115

**Comment by jkbits1** [comment]
hi @sasjkia I think this can be closed now. If you think otherwise, just let me know
