### ISSUE TITLE
Navigation is not rendering Facebook and Youtube social buttons.

### ISSUE THREAD

**Issue by geoffreyyip** [voteamerica/voteamerica.github.io#279]
The navigation bar is supposed to have a section with Youtube, Facebook, and Twitter buttons. Currently, only the Youtube button is rendering:

![Current Navigation Bar](https://cloud.githubusercontent.com/assets/15312106/26073466/fd5d5f6a-397c-11e7-93f7-09c8d6e57fbb.png)

Facebook and Twitter buttons are loaded from the Facebook and Twitter developer portals respectively. The code needs to be updated for both buttons to render properly. Please check the following websites:
* [Tweet Button](https://dev.twitter.com/web/tweet-button)
* [Share Button](https://developers.facebook.com/docs/plugins/share-button/)

Please note that the Facebook SDK is already loaded within the Jekyll app... somewhere. It may need updating.

The Youtube button can be left as is. It's a basic hyperlink element styled within this repo at `styles/main.css` through the `.social__youtube` CSS selector.

The navigation bar can be found at `_includes/nav.html`. It loads on almost every page.

**Comment by richardwestenra** [comment]
They look fine to me on both live and my local Jekyll server (in Chrome on MacOS):
![image](https://cloud.githubusercontent.com/assets/1155816/26204490/d25fb16c-3bd6-11e7-9559-9e4a55f8b8d1.png)

@geoffreyyip Can you please supply more information about steps required to replicate this issue?

**Comment by geoffreyyip** [comment]
@richardwestenra Disregard. I have blocker extensions installed on my Chrome and Firefox browsers. Nav bar renders fine when I turn them off.

**Comment by richardwestenra** [comment]
@geoffreyyip Great, no worries :)
