### ISSUE TITLE
Issues with rider phone number input

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#281]
- [ ] Rider is able to submit signup form without specifying whether phone number is for a cell phone or not. 
Please force rider to complete this selection before they are able to submit the form.

- [ ] Rider is able specify SMS as a preferred contact method from driver, even when specifying that the phone number is not a cell phone number. 
Please force the rider to change input to a cell phone number, or change the preferred contact method, if they specify SMS as preferred contact method.

[Issue #144](https://github.com/voteamerica/backend/issues/144) on the backend deals with the notification stories surrounding this.

**Comment by sasjkia** [comment]
@richardwestenra there is a related issue on the backend. Do you see any issues from a UX perspective?

**Comment by richardwestenra** [comment]
The mobile checkbox should be required, then.

However as mentioned on the backend issue, we might be able to replace this with programmatic phone number checking: https://github.com/voteamerica/backend/issues/144#issuecomment-302962745

**Comment by sasjkia** [comment]
@richardwestenra programmatic phone number checking would be awesome!

**Comment by jkbits1** [comment]
@sasjkia closed for reasons mentioned on the backend issue https://github.com/voteamerica/backend/issues/144#issuecomment-422561968
