### ISSUE TITLE
Change all mentions of phone number

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#285]
We have a new phone number. It's 540-656-9388

**Comment by geoffreyyip** [comment]
Is the old number 804-239-3389?

**Comment by sasjkia** [comment]
Yes.

**Comment by sasjkia** [comment]
@geoffreyyip thanks for taking this on.

@richardwestenra this is the most important issue right now because people need the right phone number to be able to use the service.
