### ISSUE TITLE
update tweets for 2017

### ISSUE THREAD

**Issue by jkbits1** [voteamerica/voteamerica.github.io#288]
@sasjkia re your ASAP call for updating reference to the 2016 election - please can you provide updated versions for these tweets, then I'll make the changes

UPDATE: https://github.com/voteamerica/voteamerica.github.io/pull/289 addresses the text of home pages (and others) but not the thanks page tweet

home page (and others) tweet
`Support #Democracy4All this #` Election2016 `. Sign up on @CarpoolVote: Linking drivers with voters needing a ride`

thanks page tweet
`I've signed up to offer a ride to a fellow American on @CarpoolVote. #` *Election2016* ` will be close. #CountEveryVote`

**Comment by sasjkia** [comment]
Thanks for spotting these @jkbits1!

I think the thanks page has 2 different tweets: 1 for rider, the other for driver.

Rider
I've signed up to #ClaimMyVote this #election through CarpoolVote.com. Will you? @CarpoolVote connects volunteer drivers and voters.

Driver
I've volunteered to drive voters this #election through CarpoolVote.com. Will you? @CarpoolVote #DriveToVote #RightToVote

**Comment by jkbits1** [comment]
@sasjkia great, I'll change these 👍

**Comment by ArmandoAmador** [comment]
is this still needed?

this is the current text 

```
Support #VotingRights in 2017 #USelections. Sign up via @carpoolvote: Linking drivers with voters needing a ride. http://carpoolvote.com
```

**Comment by richardwestenra** [comment]
Thanks @ArmandoAmador, you're correct, this is no longer relevant. Closing for now, but we'll need to update 2017 to 2018 in a couple of months ;)
