### ISSUE TITLE
Add 'My Rides' to Homepage nav bar

### ISSUE THREAD

**Issue by kylejcrawford** [voteamerica/voteamerica.github.io#292]
This should take a person to the self-service portal if they want to check on their rides at some point. Currently, it is difficult to do this from the homepage.

Also, I'm suggesting this phrasing because it seems like it'll work well for drivers and riders mutually.

Once this is added to the nav bar, also take the 'self-service portal' link off of the footer.

**Comment by richardwestenra** [comment]
Note: The trickiest thing about this task will be ensuring that it doesn't break the layout across different screen widths, because the header design is already a little tight in terms of space available.

**Comment by russon77** [comment]
i've attempted to resolve this in PR #303 :+1:

**Comment by richardwestenra** [comment]
Closing this issue in favour of #313 which is practically a duplicate.
