### ISSUE TITLE
Change "Seats required" text on rider signup form

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#296]
Change from:

> Please let us know how many people will need to travel together in the same car.
To make it easier for us to match people, please complete an individual form if you do not need travel with anybody else.

To:

> Please let us know how many people will need to travel together in the same car. You may take somebody with you as a safety measure.
To make it easier for us to match people, we ask that you travel with as few people as possible.

**Comment by russon77** [comment]
got it 👍
