### ISSUE TITLE
Make all link open in new tab

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#298]
Currently, clicking on a link takes people away from the site (this had somehow been reversed from the version we had last year).

Please make each link open a new tab instead.

**Comment by richardwestenra** [comment]
Note: This is a contentious issue in UX land: Many UX experts (UXperts?) argue that forcing links to open in new tabs is confusing for computer-illiterate users (as it breaks the back button), and annoying for expert users (as it takes away control from the user). See [this article on Smashing Mag](https://www.smashingmagazine.com/2008/07/should-links-open-in-new-windows/) for example.

Then again, [some argue the opposite](http://uxmovement.com/navigation/why-external-links-should-open-in-new-tabs/).

Paging @kylejcrawford.

**Comment by kylejcrawford** [comment]
Haha yeah what @richardwestenra said! Good arguments both ways (thanks for linking articles).

I'd say the trend is moving in the direction of not opening in new tabs/windows automatically

**Comment by jkbits1** [comment]
@sasjkia with the system now focusing on supporting operators there is less developer/design time for this so closing. We can re-open later if necessary (and if we can agree on which behaviour is best 🙂 )
