### ISSUE TITLE
Needs Discussion: Rider Signup > Vehicle Requirements

### ISSUE THREAD

**Issue by geoffreyyip** [voteamerica/voteamerica.github.io#300]
The **Rider Signup > Vehicle Requirements** section may need updating. Guidance text is displayed within the **Other Requirements** `<textarea>` input and also beneath it. This is inconsistent with the **Location Details** section up top. How should we redesign this section?

The objective of this issue is to discuss next steps. Once we determine that, we can create a new issue for implementation. 

From the live website:
![Location Details](https://cloud.githubusercontent.com/assets/15312106/26556442/8c226ff6-4468-11e7-9c52-6e4b3ce28875.PNG)
![Vehicle Requirements](https://cloud.githubusercontent.com/assets/15312106/26556458/98628382-4468-11e7-908a-39a64e33adfd.PNG)

From discussion in #289:

@sasjkia:
> Also, @kylejcrawford do we still need the guidance text inside the box if it is also underneath? Should we change that text?

@sasjkia:
>also, do you think this text on the desktop interface would be more convenient if next to the box, rather than underneath it?

@kylejcrawford: 
> @sasjkia There is no need to duplicate the guidance text inside and outside the box. And because in the Location Details section earlier in the sign-up process the guidance text is within the text boxes, it'd make sense to be consistent and do that in the Vehicle Requirements section also.
>
> It'd be worth simplifying this copy though to something like: "Please let us know of any other accommodations you will need."

Discussion continues below.

**Comment by geoffreyyip** [comment]
I'm personally leaning towards @kylejcrawford's viewpoint. Simplifying the copy for **Vehicle Requirements** to something like "Please let us known of any other accomodations you will need".

So something like:
* Label: Other Notes
* Placeholder: Please let us know of any other accomdoations you will need.

@sasjkia, there's a lot of guidance text currently. I'm confused by something. The website explicitly lists a bunch of scenarios like service animals, assistance entering the vehicle, and bringing a child. If these are common issues, why don't we create explicit checkboxes for these scenarios?

**Comment by sasjkia** [comment]
@geoffreyyip I think checkboxes would put too much emphasis on this text. It would alse create additional database entries for the backend. I like the suggestion about simplifying the text inside the box and then outlining potential types of input right next to it.

**Comment by sasjkia** [comment]
FYI - the original text wording was created with the help of disability charities who wanted people to have a way to communicate special accommodation needs.

**Comment by sasjkia** [comment]
@geoffreyyip "On the driver signup form in the notes page, create a separate bullet point for each type of accommodation needed. After car seat requirements, add "- Can only communicate in a language other than English"

**Comment by richardwestenra** [comment]
I believe this issue is resolved.
