### ISSUE TITLE
reduce download size

### ISSUE THREAD

**Issue by russon77** [voteamerica/voteamerica.github.io#302]
looking into the site's performance, i noticed that the site downloads a few rather large facebook and twitter libraries - but i could not identify where they were used. i think that we can configure the "tweet/share this on x platform" *without* downloading the javascript libraries!

## questions

- for what is the facebook sdk + additional downloaded libs used?
- for what is the twitter widget lib used?
- are there other dependencies we can remove or reduce?

**Comment by richardwestenra** [comment]
I believe it's just using these scripts for the share buttons. They're the standard scripts recommended by Twitter/Facebook. I'm sure there's a way to do it without requiring these scripts, I just haven't really looked into it, as I figured the scripts are loaded asynchronously so they're probably not slowing down the rest of the page. Feel free to look into it if you've not got anything more pressing to work on.

**Comment by russon77** [comment]
i did some tests and here are the results:

## download size

base: 950 KB
v2-minus-fb: 775 KB
v2-minus-twitter: 925 KB
v3-minus-fb-and-twitter: 730 KB

## number of requests

base: 80
v2-minus-fb: 75
v2-minus-twitter: 79
v3-minus-fb-and-twitter: 70

## questions

- why so many analytics tools? i see gosquared.com, google analytics, cloudflare analytics?

**Comment by richardwestenra** [comment]
Great work, thanks @russon77! I'd be interested to see how these affect page load time (specifically time to interactivity). While I have no doubt that these libs affect total download, they probably don't affect page load time so much because I believe they're async.

@sasjkia why do we have so many analytics tools?

**Comment by sasjkia** [comment]
@richardwestenra I was unaware of these tools... I know about gosquared because I get email updates on usage stats but I'm not sure who keeps paying for it but it's not me! :D

**Comment by richardwestenra** [comment]
I've created a dedicated task for removing the twitter/facebook widgets: #337
