### ISSUE TITLE
Update "Our story" to be clearer about where rides are needed

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#304]
A partner got in touch to stress that rides to the polls are essential where very specific voter suppression mechanisms are in place. In some states, it may be more effective promoting other ways to access democracy. With this in mind, please add a link underneath the paragraph "Our story" page, underneath the paragraph:
> These barriers - along with others introduced since the change - affected everybody but especially people of color, people with disabilities, young people, elderly people, and women.
[
Find out if your state is affected](https://www.letamericavote.org/states/)

**Comment by russon77** [comment]
got it :+1:
