### ISSUE TITLE
Move "I can only communicate in a language other than English" to the notes bullets

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#305]
We do not want to make more updates to the database and this format doesn't allow for the user to be specific about the language, so we cannot have this extra feature that has just been added.

- [ ] Please remove the "I can only communicate in a language other than English." check box.
- [ ] Instead, add the same sentence as a bullet point under "Other requirements".
- [ ] Please change the final "Etc." bullet in this list to "Other".
- [ ] Please move all of these bullet points next to the box, rather than underneath

Thank you! :)

**Comment by russon77** [comment]
got it :+1:
