### ISSUE TITLE
Add spam folder reminder to rider confirmation page

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#306]
On the confirmation page after a rider has submitted a ride request form, please add, underneath the first paragraph 
> on taking this step to claim your vote! We’ve sent you a message confirming that we’ve received your request.

"**If you do not receive a message via email, please check your spam folder.**"

Please make this bold, so people do not miss the memo.

**Comment by russon77** [comment]
got it
