### ISSUE TITLE
Replace 'Voting info' link with 'My rides' in nav bar

### ISSUE THREAD

**Issue by kylejcrawford** [voteamerica/voteamerica.github.io#313]
In follow-up to Issue #303

I suggest we make the Nav bar read "Our Story | How It Works | My Rides"?

This will get these all on one line and keeps the Nav bar pieces dedicated to Carpool Vote. This fits with our target users' needs because rather than learning about voting eligibility, they are primarily visiting to give/get rides to vote. Voting Info section can still be included below on the page.

Also, 'Voting Info' was the only link in the Nav that sent a person further down the page, rather than to a new page, like "Our Story" and "How it Works", so we get consistency in what the links do as well.

**Comment by evelynStraigt** [comment]
Is this what you guys needed?  =D
https://github.com/voteamerica/voteamerica.github.io/pull/322
