### ISSUE TITLE
Rider signup: Change guidance text in 'Other Requirements'

### ISSUE THREAD

**Issue by kylejcrawford** [voteamerica/voteamerica.github.io#315]
The current version includes an excess of copy. Because we have included the examples listed to the right of this text box, perhaps we can simply include text inside the box that says: 'Please let us know any other requirements you have for your ride...'

Basic mockup:
![change other requirements text box copy](https://user-images.githubusercontent.com/28900672/26886333-0d3223b4-4b73-11e7-9816-6cffb7d21a9f.png)

**Comment by florida** [comment]
assigning this to me
