### ISSUE TITLE
Problem with the date picker

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#317]
I initially tried to use a demo laptop for the presentation last night but it wouldn't let me submit the form, so I had to switch to my own laptop. Weirdly, they're both Macbooks, but the date picker looked different between them (the one had autocomplete; the other didn't).

The error message for the form submission made it look like there was a date submission issue. It looked like it could have had something to do with 24-hour clocks (although the input on the form was in 12-hour clock, as per the american convention). Not sure though because this was all in a rush.

Please could we investigate the issue with the date picker?

**Comment by jkbits1** [comment]
@sasjkia closed as not reproduced - do let us know if it occurs again
