### ISSUE TITLE
Uneven ability to accept browser font-size preferences

### ISSUE THREAD

**Issue by BNewing** [voteamerica/voteamerica.github.io#328]
Across the CSS files, there are around 26 font-size declarations, and around half are in ems and half are in px. The advantage of ems is that it accepts and scales around whatever the user may have set their standard font-size to. 

I don't think this is very widely used, and at the moment because of some ems being used, a lot of the website does scale up and down accordingly. Upon a quick scan, it seems to be mostly the headings that don't scale, which are already big. So this is quite a minor thing :)

If I get time, I might have a go at it :)

**Comment by richardwestenra** [comment]
Great call, thanks @BNewing!
