### ISSUE TITLE
Map: Show an icon for powerchair vehicles

### ISSUE THREAD

**Issue by richardwestenra** [voteamerica/voteamerica.github.io#334]
Vehicles equipped with powerchair lifts must somehow be easily flagged on the map so operators can tell if one is available.

**Comment by jkbits1** [comment]
This issue is mentioned in #336

**Comment by jkbits1** [comment]
Fixed by https://github.com/voteamerica/voteamerica.github.io/pull/364

Shows a `W` for that driver on the map
