### ISSUE TITLE
Replace Facebook & Twitter widgets in the header with plain styled links

### ISSUE THREAD

**Issue by richardwestenra** [voteamerica/voteamerica.github.io#337]
![image](https://user-images.githubusercontent.com/1155816/32888039-e7d945b4-cabd-11e7-89c7-aeaeed783f65.png)
At present, the Facebook and Twitter buttons in the header are generated with the official widgets. However these require an unnecessarily large JS download, and they load slower than the Youtube link (which is currently hard-coded and styled with CSS).
So, let's remove the widget JS and make our own, faster buttons! Copy the [Youtube button styling](https://github.com/voteamerica/voteamerica.github.io/blob/master/styles/main.css#L235-L260) but change the icon, text and background colour (remember to add a hover colour too). 
You can make the link something like this:
```
<a href="[URL]" onClick="MyWindow=window.open('[URL]','MyWindow',width=600,height=400); return false;">[Button text]</a>
```
For the [URL], you'll want to get the current URL that each one directs to. If you have a clever solution for generating the URL without needing a whole load of JS, I'm open to it!

**Comment by MichaelE1** [comment]
Hi. I can work on this! Should have a PR done within the next couple of hours.
