### ISSUE TITLE
Front End - Update all 2017 references to 2018

### ISSUE THREAD

**Issue by PamelaJohn** [voteamerica/voteamerica.github.io#341]
Update all 2017 references to 2018.

**Comment by tws9797** [comment]
Hi , may I work on this issue?

**Comment by stephenscapelliti** [comment]
Hi, @tws9797!  Thank you for your offer and your patience. As you can see, we're undergoing a change in direction from being a public-facing to an org-facing app.  I'll ask one of the team members to check in on this and get back to you.  So sorry for the delay.

**Comment by dmilet** [comment]
It’s ok with me. @PamelaJohn any particular text to be updated?

**Comment by MadhavBahlMD** [comment]
Alright @stephenscapelliti  :)

**Comment by jkbits1** [comment]
@PamelaJohn this is done now, I think. Just re-open if not (preferably with an example)

Thanks, everyone 🙂
