### ISSUE TITLE
Create auto-import of NGP Van turfs (riders data) to the CPV database

### ISSUE THREAD

**Issue by PamelaJohn** [voteamerica/voteamerica.github.io#344]
_(This request was made at the 2018, March 18th CPV upgrade planning and strategy session.)_ 

#### Create auto-import of NGP Van turfs which identify riders' data to the CPV database, including:

- Rider's Name
- Rider's Address
- Rider's Zip Code
- Rider's Phone Number
- Rider's Polling Place Address + Zip Code 

@acqsysandrea please let me know if I've missed anything data to import from turfs.

**Comment by aaghevli** [comment]
Digging into this a bit and am a bit confused. NGP Van does have API access capabilities, but I am not clear what the "turfs" refers to. 

Here is the endpoint to fetch all the contacts in a single NGP Van database: https://developers.ngpvan.com/van-api#people

We also require an API-KEY to do this work. Is this something that can be provided?

**Comment by jkbits1** [comment]
@aaghevli thanks for taking a look at this 👍 😄 much appreciated. Good point about "turfs", it has a clear meaning for election organisers @PamelaJohn @acqsysandrea can you help to clarify this, please?

@PamelaJohn @acqsysandrea @andrewcuan @aaghevli  when this issue has been discussed, I've wondered a bit about the context it fits into. If it's an occasional task, it might be easiest to have a standalone task that is provided with a text file with the data, and inserts it into the db. In which case, we run the standalone app manually (or as a background task, etc.) as and when we create the revised text file. Or does this data changes frequently and in small chunks, so we need a method that grabs the data on a frequent basis?

**Comment by aaghevli** [comment]
@acqsysandrea and I synced offline and she sent me the file, which is in PDF.

What generates this file? If this is from NGP Van CRM [1] then I wonder if they have a more computer friendly format like CSV/JSON/XML since PDF is not ideal and can lead to brittle import logic. Otherwise, the direct API access is still an option. 

@jkbits1, I am happy to help with either the stand alone task and/or polling process. 

[1] - https://blog.ngpvan.com/product/introducing-ngp-vans-new-turf-management-tool

**Comment by acqsysandrea** [comment]
I can certainly generate this is a .CSV file but there would be a lot of
manual copying and pasting. VAN does not let you export data, it is a
permission based process that is hit and miss. The .PDF files or lists are
native.

I can run the list and then copy and past the names into Excel. I would
then need to run the turf to get the polling locations and copy and paste
those in.

It is doable.

Andrea Miller

**Comment by aaghevli** [comment]
Thanks @acqsysandrea! I don't think copy and pasting is worth your time. There are two solutions:
* parse the PDF and import into the database
* directly access the VAN data via their API

I can see how far I get with the parsing of the PDF, but I would suggest thinking through the API access as it would reduce all manual work on your end entirely.

**Comment by acqsysandrea** [comment]
There may be a third option. If we load the polling locations and then
match those with the precincts. We should be able to get that data through
ESRI. Then I could just run the list and include voting precinct.

Andrea Miller

**Comment by aaghevli** [comment]
I have been able to extract the data from the PDF. I still think its really brittle and could break easily, but the output is as follows. The zip and state of the polling location is not in the polling location which makes that output incomplete:

```
{
    "name": "Harvey, Larry S",
    "phone_number": "(123) 123-1234",
    "address_lines": [
      "1234 Young Larry Rd NW",
      "Roanoke, VA 24017"
    ],
    "polling_location": "NINTH BAPTIST CHURCH, 1111 Z St"
  }
```

It is unlikely that I'll have time to finish the push to the database, but hopefully I can post a PR for at least the parsing.

**Comment by acqsysandrea** [comment]
Don't worry about posting since the primarybixn'to up ntil June. We have a
working concept.

If I send you a .CSV then you're in good shape. I will work on getting
precinct added to the output.

Andrea Miller

**Comment by aaghevli** [comment]
Thanks @acqsysandrea, the extraction into JSON from the PDF should avoid the need for you to manually extract the CSV values by hand.

**Comment by acqsysandrea** [comment]
When I generate the list, I can just do a quick swipe and copy the names.
There will never be more than a few hundred in each state.

Andrea Miller

**Comment by jkbits1** [comment]
@PamelaJohn changed the title for clarity 🙂

**Comment by jkbits1** [comment]
@stephenscapelliti think this is ready to close - do you want to archive the conversation?
