### ISSUE TITLE
Back End - Organization registry - Bug

### ISSUE THREAD

**Issue by PamelaJohn** [voteamerica/voteamerica.github.io#345]
_(This request was made at the 2018, March 18th CPV upgrade planning and strategy session.)_

#### Rider Zip Code & Polling Place Zip Codes Are Not Always the Same

Most of the time, the residential zip code of the rider and the rider's polling location are the same. But in some instances, they are not. 

How can operators determine whether the polling location zip code is different from the rider's home address zip code?

@acqsysandrea please let me know if I've mis-stated anything.

**Comment by acqsysandrea** [comment]
Operators can lookup the polling location by name and manually get the
address and I code.

Andrea Miller

**Comment by jkbits1** [comment]
@PamelaJohn @acqsysandrea riders enter both their zip and their destination address and zip. Does this cover the issue mentioned here?

**Comment by PamelaJohn** [comment]
Hi @jkbits1! Judging from the above comment from @acqsysandrea, it appears the answer to your question is "yes" and this issue can likely be closed. The problem seems to have been my misinterpretation of the issue as it was presented during the 2018.03.18 CPV upgrade planning and strategy session. Apologies!

**Comment by jkbits1** [comment]
Hi @PamelaJohn no problem at all 😄  always better to raise an issue then close than let issues go unnoticed!
