### ISSUE TITLE
Back-end - Driver registry

### ISSUE THREAD

**Issue by andrewcuan** [voteamerica/voteamerica.github.io#346]
As a field manager, I want to be able to see a list of all drivers so that they can be properly assigned to riders based on their needs and location.
**Acceptance Criteria**
- [ ] - Driver ID (auto generated)
- [ ] - Driver first name (Free text)
- [ ] - Driver last name (Free text)
- [ ] - Driver email (Free text)
- [ ] - Driver phone (Free text)
- [ ] - Preferred contact method (Dropdown)
    - Phone
    - SMS
- [ ] State
- [ ]  Number of seats (Free text)
- [ ] - License plate (Free text)
- [ ] - Has insurance (Y/N)
- [ ] - Multi-lingual (Y/N)
- [ ] - Additional languages
- [ ] - Background check complete (Y/N)
- [ ] - Car type (Drop-down)
    - Sedan
    - SUV
    - Church van
    - Church bus
    - Power chair
- [ ] Org ID (Drop down) - link to all Org IDs in the organization list

**Comment by jkbits1** [comment]
@andrewcuan as mentioned in #359 there is new functionality here for specific data fields:

those fields are State, Multi-lingual and Car type (btw, system does support Power chair support and seat count), Background check (considered and dropped for Nov 16) and Org ID

If we can move those changes to a separate issue, this issue becomes more clear-cut and easier to begin work on. Any debate on the new data will not impact work on this issue.

**Comment by jkbits1** [comment]
@acqsysandrea @aaghevli following our meeting, just pinging about these as discussed

**Comment by jkbits1** [comment]
The operator page provides all the info specified except those that depend on new functionality. The new functionality is address by issue https://github.com/voteamerica/voteamerica.github.io/issues/359
