### ISSUE TITLE
Back-end - Rider registry

### ISSUE THREAD

**Issue by andrewcuan** [voteamerica/voteamerica.github.io#347]
As a field manager, I want to be able to see a list of all riders so that they can be properly assigned to drivers based on location and needs.
**Acceptance criteria**
- [ ]  Rider ID (Auto generated)
- [ ] - Rider First Name (Free text)
- [ ] - Rider Last Name (Free text)
- [ ] - Trip date (Free text)
- [ ] - Trip time (Free text)
- [ ] - Pickup address (Free text)
- [ ] - State (Free text)
- [ ] - Pickup zip code (Free text)
- [ ] - Destination Address (Free text)
- [ ] - Destination zip code (Free text)
- [ ] - Number of Seats Required (Free text)
- [ ] - Rider have powerchair? (Y/N)
- [ ] - Voting Assistance (Y/N)
- [ ] - Two-way trip (Y/N)
- [ ] - Special needs? (Free text)
- [ ] - Rider Email (Free text)
- [ ] - Rider Phone number (Free text)
- [ ] - Rider status (Drop down list)
     - Requested
     - Accepted
     - Completed
- [ ] - Preferred Contact Method (Free text)
     - Phone
     - SMS
     - Email
- [ ] - Agree to terms? (Y/N)
- [ ] - Trip type (Drop down)
     - Two-way trip
     - One-way trip

- [ ] - Org ID (Drop down) - link to all Org IDs in the organization list

**Comment by jkbits1** [comment]
@andrewcuan as mentioned in #359 there is new functionality here for specific data fields:

those fields are State, Voting Assistance and Org ID

If we can move those changes to a separate issue, this issue becomes more clear-cut and easier to begin work on. Any debate on the new data will not impact work on this issue.

**Comment by jkbits1** [comment]
@acqsysandrea @aaghevli following our meeting, just pinging about these as discussed

**Comment by jkbits1** [comment]
The operator page provides all the info specified except those that depend on new functionality. The new functionality is address by issue #359
