### ISSUE TITLE
Front-end - Advise potential users of new operator-focused system

### ISSUE THREAD

**Issue by PamelaJohn** [voteamerica/voteamerica.github.io#348]
_(This request was made at the 2018, March 18th CPV upgrade planning and strategy session.)_

#### Problem: Site is Still Consumer-Facing, Needs Notice to Consumers

Although Sasjkia and the CPV team have made the decision to re-purpose CPV from a consumer-facing application to an outreach tool for voter-outreach organizations, there is no notice on the site advising users of the transition. 

#### Solution: Put Up Notice on Site to Manage Expectations

- [ ] Put up a notice on the website advising consumer users of changes. 
- [ ] Consider giving consumer users an alternative way to arrange a ride to the polls, via listing of voter outreach orgs and contact info
- [ ] Consider giving voter outreach organizations a way to contact ProgCode and @acqsysandrea for onboarding and training sessions.

**Comment by jkbits1** [comment]
@acqsysandrea @aaghevli following our meeting, just pinging about these as discussed

**Comment by jkbits1** [comment]
@PamelaJohn good points - further discussion needed
