### ISSUE TITLE
Back-end - Trip registry

### ISSUE THREAD

**Issue by andrewcuan** [voteamerica/voteamerica.github.io#350]
As a field manager, I want to be able to see a list of trips so that I can see how many trips are scheduled and by who.
**Acceptance criteria** 

- [ ] Trip ID (Auto-generated)
- [ ] Trip Date (Pulled from rider registry)
- [ ] Trip Time (Pulled from rider registry)
- [ ] Driver’s name (Pulled from driver registry)
- [ ] Driver ID (Pulled from driver registry)
- [ ] Pickup address (Pulled from rider registry)
- [ ] State (Pulled from rider registry)
- [ ] Pickup zip code (Pulled from rider registry)
- [ ] Destination (Pulled from polling location registry)
- [ ] Destination zip code (Pulled from polling location registry) 
- [ ] Assigned riders (Pulled from rider registry)

**Comment by jkbits1** [comment]
@andrewcuan as mentioned in #359 there is new functionality here for specific data fields:

those fields are State, Assigned riders (system currently supports a single rider for a match)

If we can move those changes to a separate issue, this issue becomes more clear-cut and easier to begin work on. Any debate on the new data will not impact work on this issue.

**Comment by jkbits1** [comment]
@acqsysandrea @aaghevli following our meeting, just pinging about these as discussed

**Comment by jkbits1** [comment]
The operator page provides all the info specified except those that depend on new functionality. The new functionality is address by issue #359
