### ISSUE TITLE
Back End - Organization registry - notifications if polling place has been closed

### ISSUE THREAD

**Issue by PamelaJohn** [voteamerica/voteamerica.github.io#355]
As a field organizer, when a volunteer driver notifies me of a sudden polling place closure or relocation, I want to be able to bulk update the polling place address for all affected voters in a dataset via NGP Van and auto-import the new list to CPV so additional riders and drivers are notified of the change in polling location.    

See Issue #344

**Comment by jkbits1** [comment]
@PamelaJohn currently, the system doesn’t maintain the polling place address for a rider, it simply records the rider’s destination zip.

@acqsysandrea @PamelaJohn @andrewcuan I'm aware we've discussed this, but is further design needed for what is required here?

**Comment by jkbits1** [comment]
@acqsysandrea @aaghevli following our meeting, just pinging about these as discussed

**Comment by jkbits1** [comment]
@PamelaJohn Closing this as not possible to implement any further features prior to mid-terms and any related issues will be discussed afterwards
