### ISSUE TITLE
Report Voter Harassment and Disenfranchisement

### ISSUE THREAD

**Issue by brotherjack** [voteamerica/voteamerica.github.io#369]
I used to do elections work for ACORN, and I know one issue we were constantly on the lookout for was harassment of voters and potential disenfranchisement. This could be everything from polling officials claiming that a voter was removed from the voting rolls, cops being stationed outside of certain polling places, refusing proper identification, and similar attempts to restrict voter involvement, particularly in communities of color. We would provide people with a number to call if they ran into issues like this.

I think this is a feature we could usefully incorporate into this project. My rough idea would be a web form that would allow a user (either a driver or a rider) to provide an incident report, which could then be forwarded to the organizers using the application. At minimum this would be a simple form that would be timestamped, have basic contextual information like address of the incident, and space to describe the incident. A more developed version might include a means of uploading media such as pictures and video related to the incident, among other things.

**Comment by PamelaJohn** [comment]
I really love this idea @brotherjack. It addresses the concerns @acqsysandrea brought up in previous meetings about the need for riders and drivers to have some flexibility when they show up at a designated polling place and find it has closed early or been moved across town or has run out of ballots, etc.

**Comment by stephenscapelliti** [comment]
One quick partial solution would be to add to the site this link for reporting federal voting rights violations: https://www.justice.gov/crt/complaint/votintake/index.php

State laws also govern voting rights, but they vary from state-to-state. Some research of state laws will be necessary to determine whether we can create a universal form for reporting state law election violations, and then couple it with a means of forwarding to the appropriate state enforcement agency.

**Comment by jkbits1** [comment]
@stephenscapelliti @PamelaJohn @brotherjack I'm closing this as it is dealt with by Andrea's (possibly with assistance from DemLabs). We can re-open for further discussion if required. 

It's preferable to re-open after the mid-terms as volunteers for last-minute tasks won't be distracted - feel free to comment below (or disagree) at any point, though
