### ISSUE TITLE
Tweet text on website has wrong year

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#394]
The Tweet button on the home page generates text that refers to a previous year, and is not clear about Carpool Vote's current status. People are still using and Tweeting this text, which is causing confusion amongst voters.

Please update the Tweet text to the following:
Support #VotingRights in 2018 #USelections through @carpoolvote: Linking drivers with voters needing a ride. http://carpoolvote.com

**Comment by jkbits1** [comment]
@sasjkia well spotted, thanks 👍
