### ISSUE TITLE
Updates to CarpoolVote landing page

### ISSUE THREAD

**Issue by stephenscapelliti** [voteamerica/voteamerica.github.io#406]
Modify the following at http://carpoolvote.com/:

**1.** Remove the legend `CARPOOL VOTE IS NOT CURRENTLY TAKING SIGNUPS` from the top of the landing page. Determine whether completion of this task eliminates the need for [Issue #393](https://github.com/voteamerica/voteamerica.github.io/issues/393)  

**2.** Change UK spelling of "organisations" (which occurs **twice** in this paragraph) to US spelling "organizations":
`The next version of Carpool Vote will empower organisations like the NAACP and AAPD to sign up their own drivers and riders through a dedicated partner portal. You'll be able to access a list of all partner organisations in your area on the new Carpool Vote site.` 

**3.** The site preview still includes the message `Get a ride or share a ride in the 2016 US presidential election.`  Consider changing this to `Get a ride or share a ride to the polls.` or some other descriptive phrase that is more inclusive of time and purpose.

**4.** Add "If you need a ride and are unable to enter your information online, call our interactive voice response service at 804-424-5335, and an operator will contact you." to the sign-up page.

**5.**  Under `UPCOMING ELECTIONS`, correct "Balltotpedia" to "Ballotpedia" (2 instances).

**6.**  Under `HOW TO CLAIM YOUR VOTE`, correct "Rock the Vote" to "Rock The Vote" (2 instances).

**Comment by stephenscapelliti** [comment]
I have added items 5 and 6 to the issue, for additional text corrections.

**Comment by jkbits1** [comment]
@stephenscapelliti thanks, you've made it easy to find these and the required action is clear 👍  these changes will be in the new release quite soon 🙂

**Comment by jkbits1** [comment]
Fixed by #408
