### ISSUE TITLE
Form update to MASTER AND DEVELOP BRANCH: Preferred method of contact

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#42]
In the RIDER signup form, add the following text below the contact details:

How would you prefer the driver to get in touch to arrange the ride?:
꧐ Email		꧐ SMS		꧐ Phone call

**Comment by dmilet** [comment]
Updated DB schema accordingly.
RiderPreferredContactMethod | character varying(20)

RIDER form, the input element name should be RiderPreferredContactMethod
@sasjkia :
Values should be one of
[blank]   <--- DB will allow this, but do you want to allow this in the UI ? 
Email
SMS
Phone

**Comment by sasjkia** [comment]
mmm... i think multiple checks would be ok but not none
