### ISSUE TITLE
Form update in MASTER AND DEVELOP BRANCH: Vulnerable passenger matching

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#43]
In DRIVER signup form, underneath phone number entry, include the following entry:
I am driving in an official capacity on behalf of a registered organization ꧐
Organization registration number: ______________ (required if the above box is checked)

In RIDER signup form, underneath the phone number entry, include the following entry:
꧐ Pensioner or disability: Please check this box if you are retired from work or you consider yourself to have a disability

Do you have an special accommodation needs?

**Comment by dmilet** [comment]
Back end is OK.
For the DRIVER form, make sure you use those input names  :
DrivingOnBehalfOfOrganization (checkbox)
DrivingOBOOrganizationName (text box)
 
For RIDER form, please make sure you use 
RiderIsVulnerable (checkbox)
