### ISSUE TITLE
Change location information provision in signup forms in MAIN BRANCH

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#45]
In RIDER signup form, delete city option:

Change "From" descriptive text inside the entry box to "Where can you meet the driver"
Change "From" to "Collection zip code"

Change "Destination" to descriptive text inside the entry box to "To where do you need a ride?"
Change "Destination" to "Destination address"

In DRIVER signup form, change City and Neighborhood to "Collection zip code" and include descriptive text inside the entry box to "Where can you collect the rider"
Below this, add: I am willing to collect within a ___ mile radius of this zip code

For the zip codes, require entry for both boxes to be 5 numerical digits only.
Ditto for miles but with 3 digits

**Comment by sasjkia** [comment]
Thanks for doing this @dbrusky1. Have you notified the backend? (we need to do this for any changes made the the main branch). Also, is there a way for the zip code numbers box to not have arrows on the side?

**Comment by dbrusky1** [comment]
I will let them know.  Glad to Help!
