### ISSUE TITLE
Create polling location finder on RIDER signup form in MASTER BRANCH AND DEVELOP BRANCH

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#50]
So riders can know where they will need to go on election day, we need a polling location finder accessible on the signup form.

Each state has a different site to check polling location. The full list is accessible here: https://docs.google.com/spreadsheets/d/1yk7mxt0kOK_HeLUbQrgjYXNMnjPxFv-gsGg7pZ8S5TU/edit?usp=sharing

On the RIDER signup form, next to the Destination box, could we please create a link: [CHECK YOUR POLLING LOCATION] This would link to the polling location checker for the relevant state, depending on what state was selected in the drop-down

**Comment by dbrusky1** [comment]
I will do this later today.

**Comment by lili2311** [comment]
@dbrusky1 I assume this is assigned to you? Do you mind assigning the ticket to yourself so we don't think it is available to pick up :)

**Comment by dbrusky1** [comment]
thanks didnt know about that.

**Comment by dmilet** [comment]
What data would you need to submit to the backend for this ?
Right now, DRIVERS indicate ZIP code and radius, while RIDERS indicate pickup ZIP code and drop-off ZIP code. 
Please let me know.
