### ISSUE TITLE
Create Captcha in MASTER AND DEVELOP BRANCH signup forms for RIDERS and DRIVERS

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#54]
We need to verify that signups were not done by bots.

Please introduce a requirement for both riders and drivers to verify they are not a bot, after they've submitted the signup form.

Something like this is accessible for all levels of tech proficiency/literacy as well as mobile devices:
http://textcaptcha.com/

**Comment by jkbits1** [comment]
@sasjkia you are making a good point. Just a thought on this. Earlier this year I attended a conference where the speaker, who was blind, got the audience to use the audio version of the standard captcha widget. It was pretty much unusable.

**Comment by sasjkia** [comment]
Thansk @jkbits1. Was that for a different Captcha or this one. If this one is not suitable, can you recommend another?

**Comment by jkbits1** [comment]
Good questions. I'll contact the speaker via twitter and hope they suggest something. I'm aware that it's not ideal to comment without a better alternative, but it may relevant to quite a few riders.

**Comment by jkbits1** [comment]
@sasjkia the speaker has replied and offered some helpful suggestions. http://textcaptcha.com is the preferred choice. Google's nocaptcha has benefits but is desktop only for now.

**Comment by jkbits1** [comment]
@sasjkia great, happy to help!

**Comment by dmilet** [comment]
Anything needed on the backend side to support this ?
