### ISSUE TITLE
Incorporate advice from disability orgs - MASTER BRANCH AND DEVELOP BRANCH

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#72]
In DRIVER signup form, change "I am able to transfer a person with a wheelchair into my vehicle" to
"I have an adapted van with space for a powerchair"

In RIDER signup form, change the text input box back to a check box (it's unlikely that more than 1 wheelchair user will need to travel in the same vehicle)
Keep the style the same as the DRIVER form - "Wheelchair" to the left of the check box, "I am a powerchair user who needs an adapted van with a lift" to the right of the box.

In the RIDER signup form, change the text inside the notes box to: "I have the following accommodation requirements (ex: service animal, assistance folding equipment, assistance entering and exiting car):"

**Comment by misteranderson** [comment]
I have a update in progress including these changes.

**Comment by dmilet** [comment]
DB Schema has been updated to support this.
On the DRIVER form, the checkbox control name should be DriverCanLoadRiderWithWheelchair
On the RIDER form, the checkbox control name should be NeedWheelchair, and the notes textbox name should be RiderAccommodationNotes
