### ISSUE TITLE
Rider signup form to use boolean checkbox for need wheelchair

### ISSUE THREAD

**Issue by dmilet** [voteamerica/voteamerica.github.io#75]
On the rider form, we should ask how may seats are needed (TotalPartySize) , and if wheelchair is needed (NeedWheelchair)

Checkbox name should be called : NeedWheelchair

<div class="checkbox">
                                            <label>
                                                <input type="checkbox" name="NeedWheelchair" value="false" id="NeedWheelchair">
                                                I need a wheelchair
                                            </label>
                                        </div>

The node.js app that will collect the data expects those 2 fields from the form : NeedWheelchair and TotalPartySize

**Comment by misteranderson** [comment]
Is this still valid?  I thought there was a change talking about a powerchair, and the notes box for other accommodations.

**Comment by dmilet** [comment]
Closing as duplicate of Issue #72
