### ISSUE TITLE
Move forms into their own pages?

### ISSUE THREAD

**Issue by richardwestenra** [voteamerica/voteamerica.github.io#80]
I'd like to suggest that we move the two homepage forms into their own pages (at `/offer-a-ride/index.html` and `/need-a-ride/index.html` or similar). Instead of using JS to show the forms, each of the main buttons would be a link.

## Pros:
- You get a working back button and sensible browser history for free.
- Your URL routing is taken care of.
- No need to write any UI logic.
- Shorter, more sensible HTML document length.
- Infinitesimally smaller upfront page load time, due to a smaller HTML doc.

## Cons:
- Users would need to load a new page when they click the buttons to fill out a form, instead of this happening instantaneously.
- Any elements that are used across the whole site would be repeated, making the code less DRY.

Thoughts?

**Comment by erikathea** [comment]
If we are to push with this, I suggest to make a common.css or common.js to eliminate the 2nd con listed. For the first con, better to get feedback from the users but I believe we are somehow psychologically trained by now that when we click a button, another page loads, and it should load fast.

**Comment by richardwestenra** [comment]
Yeah we are definitely planning to move the JS into a separate common file, as soon as we can. The styles.css file is pretty much already valid as a common CSS file so there's nothing extra required there.

As for the first con: I completely agree. I've actually done a bit more work to improve the form navigation since I first suggested this approach, so I think I'll shelve this plan for now.
