### ISSUE TITLE
date/time intervals on rider/driver forms to be submitted in ISO8601 format

### ISSUE THREAD

**Issue by dmilet** [voteamerica/voteamerica.github.io#81]
Example of such format
2016-10-01T08:00:00-0500/2016-10-01T10:00:00-0500

Right now, no data is sent in AvailableRideTimesJSON and AvailableDriveTimesJSON elements.
No matching can happen without properly formatted data.

**Comment by dmilet** [comment]
Expected format by the backend: Pipe-separated string of ISO8601-formatted intervals with timezone. For example : 2016-10-01T08:00:00-0500/2016-10-01T10:00:00-0500|2016-10-01T10:00:00-0500/2016-10-01T22:00:00-0500|2016-10-01T22:00:00-0500/2016-10-01T23:00:00-0500

**Comment by jkbits1** [comment]
@dmilet assigning this to myself to resolve it, if only for the short term

**Comment by jkbits1** [comment]
@dmilet this PR https://github.com/voteamerica/voteamerica.github.io/pull/106 addresses rider dates
