### ISSUE TITLE
Need drop-down to polling station locator + rider form design to hold address

### ISSUE THREAD

**Issue by dmilet** [voteamerica/voteamerica.github.io#82]
needed for the demo
Best I have seen is on master branch, commit 269e1aa
is a long list or hyperlinks, 1 per state,  added in the middle of the rider form. The links open a new tab. But the rider form does not have all address fields, a single field for the entire address. There is something like "collection zip code though"

purpose of this issue is to agree on the design of the UI elements and deliver for the demo

**Comment by sasjkia** [comment]
Has this been resolved?

**Comment by richardwestenra** [comment]
@dmilet I'm considering this issue resolved unless I hear otherwise
