### ISSUE TITLE
Create Captcha in signup forms for RIDERS and DRIVERS

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#91]
We need to verify that signups were not done by bots.
Please introduce a requirement for both riders and drivers to verify they are not a bot, after they've submitted the signup form.

Something like this is accessible for all levels of tech proficiency/literacy as well as mobile devices:
http://textcaptcha.com/

**Comment by richardwestenra** [comment]
I'm considering this a low priority for now, because we haven't encountered a bot problem yet. Obviously we should try to prevent the issue ever occurring, but in the meantime I'd argue that we have more pressing concerns.

**Comment by sasjkia** [comment]
@richardwestenra agreed :)

**Comment by richardwestenra** [comment]
@sasjkia Closing this issue for now because I don't want anybody else picking it up when we have more important things to do. If we get everything else done or we face attacks from bot armies then we can come back to this and reopen it.
