### ISSUE TITLE
Create youtube social media button

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#93]
This should be placed next to the Facebook and Twitter buttons

https://www.youtube.com/channel/UCY1aS3TMDGxVbckA7Va0QFA

**Comment by richardwestenra** [comment]
I'll take this.

Note to self for later: Use the button available on https://developers.google.com/youtube/youtube_subscribe_button

- Channel ID: `UCY1aS3TMDGxVbckA7Va0QFA`
- Layout: `Default`
- Subscribers: `hidden`.

Example embed code:
```
<script src="https://apis.google.com/js/platform.js"></script>
<div class="g-ytsubscribe" data-channelid="UCY1aS3TMDGxVbckA7Va0QFA" data-layout="default" data-count="hidden"></div>
```
