### ISSUE TITLE
RIDER signup form updates

### ISSUE THREAD

**Issue by sasjkia** [voteamerica/voteamerica.github.io#96]
- [x] Add rider address text input with Label 'Pick up address' and `name="RiderCollectionAddress"`, immediately above the pick up zip code.
- [x] Remove state drop-down: We no longer need this, now that we also have a polling location lookup
- [x] Add notes box just before Personal details section:
Notes: [Temporary text inside box: I have the following accommodation requirements (ex: service animal, assistance folding equipment, assistance entering and exiting car)]
- [ ] Add full destination address input boxes with autocomplete for zip code: Riders are unlikely to know their destination zip code and drivers need the full address to decide whether or not to accept a ride request `[DEPRECATED]`
- [ ] Add box for town name, that gets autocompleted once collection zip code has been entered: Drivers will need this information to decide whether or not to accept a ride. `[DEPRECATED]`
- [x] Add Preferred method of contact tick-boxes: Email / Phone / SMS
- [x] Make phone number entry compulsory
- [x] Make email address entry optional, unless this is specified as the preferred method of contact.
- [x] Add check box next to other legal ones: I understand that Carpool Vote provides introductions between riders and volunteer drivers who have signed up on the platform. I understand that anybody can sign up to drive and Carpool Vote is unable to perform any background checks on people who use the platform. As with any other environment where I meet new people, I will take steps to keep myself and my possessions safe and accept that Carpool Vote cannot be responsible if anything goes wrong.

**Comment by sasjkia** [comment]
@dmilet are these ok with the backend?

**Comment by dmilet** [comment]
Item#4. Does the form need to do the zip code->city lookup? I suppose the frontend guys would be able to do it, but we also have loaded in the db info about all zip codes, so the back end could add the information to the ride request record at form submission. 
Unless we want the user to be able to visually verify they have entered the correct zip code.
And do you want the city name also for destination zip code?

**Comment by sasjkia** [comment]
@dmilet it's necessary for origin zip code to show up in driver notification but not at frontend input stage. Backend only could work but it could be useful to limit room for error by also populating at the frontend input stage.

The ideal would be for the user to input the destination location/address and then the zip code/address would autopulate (most people know their own zip code but not the zip code of their dmv office/local school etc).

**Comment by sasjkia** [comment]
For whoever takes this issue: "Any form change is acceptable as long as it does not remove or rename any of the form input controls. new fields would be ignored until the backend is aligned, which is ok for the demo I think."

**Comment by richardwestenra** [comment]
@dmilet / @sasjkia How do you see task 1 (state dropdown removal) working? The polling location lookup is just a list of links, it doesn't populate anything for the form.

However I could imagine keeping the state dropdown in place and replacing the polling location lookup with a link that's populated and shown only when you select the relevant state from the dropdown. Thoughts?

**Comment by dmilet** [comment]
Richard, I like either approach. Seems to me, people are used to identifying their state by their two-letter code. The rider form should be clear what information is expected. Either full address, or not, matching will be based on zip code only.

**Comment by sasjkia** [comment]
@richardwestenra state is not used for matching... i think that is zip code. @dmilet am i right?
so, i think we can just remove the state drop-down and then that removes a step if people already know where they need to go.

**Comment by sasjkia** [comment]
lovely progress here! <3 i think we'll need the final amendments before we can pass on csv for partners to populate. could we prioritise these now?

**Comment by richardwestenra** [comment]
@sasjkia I'm still a little unsure about what exactly is required for the address/zip code lookup. Can you please clarify how you see this working? It might be worth discussing the user flow here. There are APIs we can use for this sort of thing (e.g. http://www.zippopotam.us/ which gives a place name when you provide a ZIP code) but I'm unsure about the UI. Maybe let's discuss over Slack?

**Comment by sasjkia** [comment]
@richardwestenra the main aim here is for the driver to receive more information than just the zip code, when there's a ride request (as it's quite tricky to know where you're meant to be driving, based on a zip code, and there won't be a map in these messages).

Is it possible for the system to guess the zip code from the address (or even better - name of place; e.g., dmv danville, va/danville high school), rather than the other way around? I'm asking because voters may not always know the zip code of their destination - it's more intuitive to type in the location.

@dmilet will be matching using sip code only.

Let me know if you'd like to discuss over Slack. :)

**Comment by sasjkia** [comment]
If any automated populating is too time-consuming at this point, can people at least be asked to input the full address, so drivers know where they need to be going?

**Comment by richardwestenra** [comment]
@sasjkia Sure thing.

@dmilet We're going to need to add a `RiderCollectionZIP` text input field to the form. That ok on your end?

**Comment by dmilet** [comment]
yes, go ahead, it will be ignored until we catch up on the back end side

**Comment by richardwestenra** [comment]
Cool, thanks.

@sasjkia Should this address input be required for form submission?

**Comment by dmilet** [comment]
Just an idea?  We already have a text field for Additional notes, can't we reuse it to store whatever information (including the pick up location) the rider wants to convey to the driver?

**Comment by sasjkia** [comment]
@richardwestenra yes pls. This is necessary for drivers to decide whether or not to accept requests.

@dmilet I think this may happen naturally as people intuit that the driver may need more info. I do think it's better as a separate box, to keep things clean and simple.

**Comment by dmilet** [comment]
fewer text boxes, fewer interactions. But if we want more, we can have more.

**Comment by pavsaiprasad** [comment]
Will pick this up.

**Comment by sasjkia** [comment]
yes pls

Sasjkia

FOUNDER AND ORGANIZER
[image: CarpoolVote.com] <http://carpoolvote.com/>

<https://www.facebook.com/CarpoolVote>    <https://twitter.com/CarpoolVote>
  <https://www.youtube.com/channel/UCY1aS3TMDGxVbckA7Va0QFA>

On Mon, Oct 24, 2016 at 10:19 AM, Richard Westenra <notifications@github.com

**Comment by richardwestenra** [comment]
@sasjkia @dmilet @pavsaiprasad Do we need to add the dropoff address field? If we can avoid it, I think we should, because it would be much more of a headache for riders than the collection address, because they won't know it off the top of their heads. Is it necessary for us to provide that to drivers, or can they just gather that info themselves?
I figure you'll probably say that it is necessary, which is cool, but I'd recommend that we at least mark the dropoff address field as `optional`.

**Comment by dmilet** [comment]
If it were up to me, we'd have a single text box nothing more than the one we have already, where riders can add whatever information they want to convey to the driver. We will not be processing nor validating the addresses, and the form is already complicated enough.

**Comment by pavsaiprasad** [comment]
@richardwestenra - agree that if it is needed, it should be optional, since the destination zip code would give the driver a rough idea of the location. 

@dmilet - if the pick up address is left optional as a part of additional information, wouldn't this cause some confusion about the exact location for the driver?

**Comment by sasjkia** [comment]
This is 100% necessary. Drivers need to know where they're going to decide whether or not to accept the ride.

Not everyone is going to a polling place and not all drivers are driving in their home zip.

**Comment by richardwestenra** [comment]
@sasjkia Okay the address inputs have been added (thanks @pavsaiprasad!) so I'm closing this issue.
